(function(){
'use strict';
var SYNC_PENDING='rb_ct_sync_pending_v1';
var BACKUP_KEY='rb_ct_backup_v1';
var DESTRUCTIVE_KEY='rb_ct_destructive_sync_v1';
var syncTimer=null,syncController=null,syncAttempts=0,syncActive=false;
window._ctMainPage=window._ctMainPage||1;
window._ctMainPageSize=window._ctMainPageSize||(window.rbPageSizeGet?window.rbPageSizeGet('links'):(parseInt(localStorage.getItem('rb_ct_page_size_v1'),10)||50));
function cloudUrl(){var base=typeof FB_DB!=='undefined'?FB_DB:'https://richbiotech-c4e41-default-rtdb.firebaseio.com';return base+'/content_tracker_v2.json'}
function trackerActive(){var team=document.getElementById('tab-team'),panel=document.querySelector('[data-sub="links"]');return !document.hidden&&!!team&&team.classList.contains('active')&&!!panel&&panel.classList.contains('gsp-active')&&!!panel.querySelector('#ct-tbody')}
function status(type,text,title){var e=document.getElementById('ct-sync-status');if(!e){var host=document.querySelector('.ct-header .ct-actions')||document.querySelector('.ct-header');if(!host)return;e=document.createElement('span');e.id='ct-sync-status';e.className='ct-sync-status';e.onclick=function(){window.ctSyncNow(true)};host.insertBefore(e,host.firstChild)}e.className='ct-sync-status '+type;e.textContent=text;e.title=title||'คลิกเพื่อซิงก์อีกครั้ง'}
function loadContentData(){try{return JSON.parse(localStorage.getItem('rb_olympplus_v1')||'[]')}catch(e){return []}}
function backupCurrentRows(next){try{var current=loadContentData();if(!current.length||JSON.stringify(current)===JSON.stringify(next))return;localStorage.setItem(BACKUP_KEY,JSON.stringify({items:current,createdAt:Date.now(),reason:'before_local_save'}))}catch(e){}}
function compactRows(items){return (Array.isArray(items)?items:[]).map(function(row){if(!row||typeof row!=='object'||Array.isArray(row))return row;var out={};Object.keys(row).forEach(function(key){var value=row[key];if(value!==''&&value!==null&&typeof value!=='undefined')out[key]=value});return out})}
function writeLocalRows(items){var rows=Array.isArray(items)?items:loadContentData();window._ctCloudRows=rows;try{localStorage.setItem('rb_olympplus_v1',JSON.stringify(rows));return true}catch(firstError){try{localStorage.setItem('rb_olympplus_v1',JSON.stringify(compactRows(rows)));return true}catch(secondError){return false}}}
function signalContentUpdated(){try{window.dispatchEvent(new CustomEvent('rb:content-updated'))}catch(e){}}
function localSave(items){backupCurrentRows(items);if(!writeLocalRows(items)){status('waiting','กำลังบันทึกออนไลน์','พื้นที่ในเครื่องไม่พอ ระบบกำลังบันทึกออนไลน์โดยตรง');return false}try{localStorage.setItem(SYNC_PENDING,String(Date.now()))}catch(e){}signalContentUpdated();return true}
function unpackCloud(data){return Array.isArray(data)?data:(data&&Array.isArray(data.items)?data.items:[])}
function longCloudFetch(options){var ctl=typeof AbortController!=='undefined'?new AbortController():null,timer=setTimeout(function(){if(ctl)ctl.abort()},90000),opts=options||{};if(ctl)opts.signal=ctl.signal;var transport=window.rbFirebaseAuth&&window.rbFirebaseAuth.fetch?window.rbFirebaseAuth.fetch:fetch;return transport(cloudUrl(),opts).then(function(response){clearTimeout(timer);if(!response.ok)throw new Error('HTTP '+response.status);return response},function(error){clearTimeout(timer);throw error})}
function cloudReadRows(){if(window.rbFirebaseAuth&&window.rbFirebaseAuth.fetch)return longCloudFetch({cache:'no-store'}).then(function(response){return response.json()}).then(unpackCloud);if(typeof window.fbGet!=='function')return Promise.resolve([]);return new Promise(function(resolve,reject){window.fbGet('/content_tracker_v2',function(error,data){if(error)reject(error);else resolve(unpackCloud(data))})})}
function consumeDestructiveAuthorization(){try{var at=Number(localStorage.getItem(DESTRUCTIVE_KEY)||0);localStorage.removeItem(DESTRUCTIVE_KEY);return at>0&&Date.now()-at<120000}catch(e){return false}}
function mergeById(remote,local){var result=(remote||[]).slice(),positions={};result.forEach(function(row,index){if(row&&row.id!=null)positions[String(row.id)]=index});(local||[]).forEach(function(row){var id=row&&row.id!=null?String(row.id):'';if(id&&Object.prototype.hasOwnProperty.call(positions,id))result[positions[id]]=row;else result.push(row)});return result}
function protectAgainstRollback(items){var local=Array.isArray(items)?items:[];if(consumeDestructiveAuthorization())return Promise.resolve(local);return cloudReadRows().then(function(remote){var suspicious=remote.length>local.length+Math.max(25,Math.floor(remote.length*.1));if(!suspicious)return local;var merged=mergeById(remote,local);backupCurrentRows(merged);writeLocalRows(merged);if(typeof _ctData!=='undefined')_ctData=merged;signalContentUpdated();status('waiting','ป้องกันข้อมูลเก่าทับข้อมูล','พบข้อมูลในอุปกรณ์น้อยกว่าฐานข้อมูล ระบบรวมข้อมูลเดิมกลับให้อัตโนมัติ');return merged},function(){throw new Error('ตรวจฐานข้อมูลก่อนซิงก์ไม่สำเร็จ')})}
function writeProtectedRows(rows){var payload={items:rows,updatedAt:Date.now(),source:'ct_reliable_'+Math.random().toString(36).slice(2,8)},opts={method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)};if(window.rbFirebaseAuth&&window.rbFirebaseAuth.fetch)return longCloudFetch(opts).then(function(){return true});if(typeof window.fbSet==='function')return Promise.resolve(window.fbSet('/content_tracker_v2',payload)).then(function(ok){if(ok===false)throw new Error('รอซิงก์ออนไลน์');return true});return longCloudFetch(opts).then(function(){return true})}
function cloudWriteRows(items){if(typeof window.fbGet!=='function')return writeProtectedRows(Array.isArray(items)?items:[]);return protectAgainstRollback(items).then(writeProtectedRows)}
function schedule(delay){clearTimeout(syncTimer);syncTimer=setTimeout(function(){syncNow(false)},typeof delay==='number'?delay:450)}
function syncNow(manual){if(manual)try{localStorage.setItem(SYNC_PENDING,String(Date.now()))}catch(e){}if(window.rbMultiTab&&!window.rbMultiTab.isLeader()){status('local','บันทึกแล้ว','แท็บหลักจะซิงก์ข้อมูลให้อัตโนมัติ');return Promise.resolve(false)}if(syncActive){if(manual)schedule(300);return Promise.resolve(false)}if(typeof navigator!=='undefined'&&navigator.onLine===false){status('waiting','รออินเทอร์เน็ต');schedule(2500);return Promise.resolve(false)}syncActive=true;status('syncing','กำลังซิงก์...');var started=Date.now();return cloudWriteRows(loadContentData()).then(function(){syncActive=false;syncAttempts=0;localStorage.removeItem(SYNC_PENDING);status('synced','ซิงก์แล้ว '+Math.max(1,Math.round((Date.now()-started)/100)/10)+' วิ.','ข้อมูลในเครื่องและออนไลน์ตรงกันแล้ว');return true}).catch(function(){syncActive=false;syncAttempts++;status('waiting','รอซิงก์ใหม่','ซิงก์ไม่สำเร็จ ระบบจะลองใหม่อัตโนมัติ');schedule([1200,4000,12000][Math.min(syncAttempts-1,2)]);return false})}
window.ctPersistContent=function(items){var rows=Array.isArray(items)?items:(typeof _ctData!=='undefined'&&Array.isArray(_ctData)?_ctData:loadContentData());if(typeof _ctData!=='undefined')_ctData=rows;if(localSave(rows)){status('local','บันทึกแล้ว','บันทึกในเครื่องแล้ว กำลังซิงก์ออนไลน์ทันที');return syncNow(false).then(function(ok){return {local:true,queued:!ok,cloud:ok};})}status('syncing','กำลังบันทึกออนไลน์...','พื้นที่ในเครื่องไม่พอ กำลังใช้ฐานข้อมูลออนไลน์แทน');return cloudWriteRows(rows).then(function(){try{localStorage.removeItem(SYNC_PENDING);localStorage.removeItem('rb_olympplus_v1');writeLocalRows(rows)}catch(e){}signalContentUpdated();status('synced','ซิงก์แล้ว','บันทึกลงฐานข้อมูลออนไลน์เรียบร้อย');return {local:false,cloud:true}},function(error){status('waiting','บันทึกไม่สำเร็จ','พื้นที่ในเครื่องไม่พอและยังติดต่อฐานข้อมูลออนไลน์ไม่ได้');throw error})};
window.ctSave=function(items){return window.ctPersistContent(items)};
window.ctAuthorizeDestructiveSync=function(){try{localStorage.setItem(DESTRUCTIVE_KEY,String(Date.now()))}catch(e){}};
window.ctSyncNow=function(){clearTimeout(syncTimer);return syncNow(true)};
window.ctMainPage=function(p){window._ctMainPage=Math.max(1,p);if(typeof ctRender==='function')ctRender();var box=document.querySelector('.ct-table-container');if(box)box.scrollIntoView({block:'start',behavior:'smooth'})};
window.ctMainPageSize=function(v){var n=parseInt(v,10);window._ctMainPageSize=[50,100,200].indexOf(n)>=0?n:50;window._ctMainPage=1;try{localStorage.setItem('rb_ct_page_size_v1',String(window._ctMainPageSize));}catch(e){}if(window.rbPageSizeSet)window.rbPageSizeSet('links',window._ctMainPageSize);if(typeof ctRender==='function')ctRender()};
window.ctRenderMainPager=function(total,start,shown,size){var table=document.querySelector('.ct-table-container');if(!table)return;var bottom=document.getElementById('ct-main-pager');if(!bottom){bottom=document.createElement('div');bottom.id='ct-main-pager';bottom.className='ct-main-pager ct-main-pager-bottom';table.insertAdjacentElement('afterend',bottom)}var pages=Math.max(1,Math.ceil(total/size)),page=Math.min(window._ctMainPage||1,pages),nums=[],from=Math.max(1,page-2),to=Math.min(pages,page+2);for(var i=from;i<=to;i++)nums.push('<button class="ct-main-page '+(i===page?'active':'')+'" onclick="ctMainPage('+i+')">'+i+'</button>');var html='<span><b>หน้า '+page+' จาก '+pages+'</b> · แสดง '+(total?start+1:0)+'–'+(start+shown)+' จาก '+total+' รายการ</span><span class="ct-main-pages"><button class="ct-main-page" '+(page<=1?'disabled':'')+' onclick="ctMainPage('+(page-1)+')">‹</button>'+nums.join('')+'<button class="ct-main-page" '+(page>=pages?'disabled':'')+' onclick="ctMainPage('+(page+1)+')">›</button><select class="ct-main-size" onchange="ctMainPageSize(this.value)"><option value="50"'+(size===50?' selected':'')+'>50/หน้า</option><option value="100"'+(size===100?' selected':'')+'>100/หน้า</option><option value="200"'+(size===200?' selected':'')+'>200/หน้า</option></select></span>';bottom.innerHTML=html;var top=document.getElementById('ct-main-pager-top');if(top)top.innerHTML=html;if(!syncActive)status(localStorage.getItem(SYNC_PENDING)?'waiting':'synced',localStorage.getItem(SYNC_PENDING)?'รอซิงก์ใหม่':'ข้อมูลพร้อม')};
window.addEventListener('online',function(){if(localStorage.getItem(SYNC_PENDING))schedule(200)});
window.addEventListener('storage',function(e){if(e.key===SYNC_PENDING&&window.rbMultiTab&&window.rbMultiTab.isLeader()){schedule(200);return}if(e.key!=='rb_olympplus_v1'||localStorage.getItem(SYNC_PENDING))return;var items=loadContentData();if(typeof _ctData!=='undefined')_ctData=items;try{window.dispatchEvent(new CustomEvent('rb:content-updated'))}catch(x){}if(trackerActive()&&typeof ctRender==='function')ctRender()});
if(window.addEventListener)window.addEventListener('rb:leader-change',function(e){if(e.detail&&e.detail.leader&&trackerActive()&&localStorage.getItem(SYNC_PENDING))schedule(150)});
document.addEventListener('visibilitychange',function(){if(trackerActive()&&localStorage.getItem(SYNC_PENDING))schedule(300)});
if(localStorage.getItem(SYNC_PENDING))schedule(250);
})();
