(function(){
'use strict';
var SYNC_PENDING='rb_ct_sync_pending_v1';
var syncTimer=null,syncController=null,syncAttempts=0,syncActive=false;
window._ctMainPage=window._ctMainPage||1;
window._ctMainPageSize=window._ctMainPageSize||(window.rbPageSizeGet?window.rbPageSizeGet('links'):(parseInt(localStorage.getItem('rb_ct_page_size_v1'),10)||50));
function cloudUrl(){var base=typeof FB_DB!=='undefined'?FB_DB:'https://richbiotech-graphic-ads-default-rtdb.firebaseio.com';return base+'/content_tracker_v2.json'}
function trackerActive(){var team=document.getElementById('tab-team'),panel=document.querySelector('[data-sub="links"]');return !document.hidden&&!!team&&team.classList.contains('active')&&!!panel&&panel.classList.contains('gsp-active')&&!!panel.querySelector('#ct-tbody')}
function status(type,text,title){var e=document.getElementById('ct-sync-status');if(!e){var host=document.querySelector('.ct-header .ct-actions')||document.querySelector('.ct-header');if(!host)return;e=document.createElement('span');e.id='ct-sync-status';e.className='ct-sync-status';e.onclick=function(){window.ctSyncNow(true)};host.insertBefore(e,host.firstChild)}e.className='ct-sync-status '+type;e.textContent=text;e.title=title||'คลิกเพื่อซิงก์อีกครั้ง'}
function loadContentData(){try{return JSON.parse(localStorage.getItem('rb_olympplus_v1')||'[]')}catch(e){return []}}
function compactRows(items){return (Array.isArray(items)?items:[]).map(function(row){if(!row||typeof row!=='object'||Array.isArray(row))return row;var out={};Object.keys(row).forEach(function(key){var value=row[key];if(value!==''&&value!==null&&typeof value!=='undefined')out[key]=value});return out})}
function writeLocalRows(items){var rows=Array.isArray(items)?items:loadContentData();try{localStorage.setItem('rb_olympplus_v1',JSON.stringify(rows));return true}catch(firstError){try{localStorage.setItem('rb_olympplus_v1',JSON.stringify(compactRows(rows)));return true}catch(secondError){return false}}}
function signalContentUpdated(){try{window.dispatchEvent(new CustomEvent('rb:content-updated'))}catch(e){}}
function localSave(items){if(!writeLocalRows(items)){status('waiting','กำลังบันทึกออนไลน์','พื้นที่ในเครื่องไม่พอ ระบบกำลังบันทึกออนไลน์โดยตรง');return false}try{localStorage.setItem(SYNC_PENDING,String(Date.now()))}catch(e){}signalContentUpdated();return true}
function cloudWriteRows(items){var ctl=typeof AbortController!=='undefined'?new AbortController():null,timer=setTimeout(function(){if(ctl)ctl.abort()},15000),payload={items:Array.isArray(items)?items:[],updatedAt:Date.now(),source:'ct_direct_'+Math.random().toString(36).slice(2,8)},opts={method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)};if(ctl)opts.signal=ctl.signal;return fetch(cloudUrl(),opts).then(function(response){clearTimeout(timer);if(!response.ok)throw new Error('HTTP '+response.status);return true},function(error){clearTimeout(timer);throw error})}
function schedule(delay){clearTimeout(syncTimer);syncTimer=setTimeout(function(){syncNow(false)},typeof delay==='number'?delay:450)}
function syncNow(manual){if(!trackerActive())return Promise.resolve(false);if(window.rbMultiTab&&!window.rbMultiTab.isLeader()){status('local','บันทึกแล้ว','แท็บหลักจะซิงก์ข้อมูลให้อัตโนมัติ');return Promise.resolve(false)}if(syncActive){if(manual)schedule(300);return Promise.resolve(false)}if(typeof navigator!=='undefined'&&navigator.onLine===false){status('waiting','รออินเทอร์เน็ต');return Promise.resolve(false)}syncActive=true;status('syncing','กำลังซิงก์...');if(syncController)try{syncController.abort()}catch(e){}syncController=typeof AbortController!=='undefined'?new AbortController():null;var timeout=setTimeout(function(){if(syncController)syncController.abort()},12000);var payload={items:loadContentData(),updatedAt:Date.now(),source:'ct_fast_'+Math.random().toString(36).slice(2,8)};var opts={method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)};if(syncController)opts.signal=syncController.signal;var started=Date.now();return fetch(cloudUrl(),opts).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);clearTimeout(timeout);syncActive=false;syncAttempts=0;localStorage.removeItem(SYNC_PENDING);status('synced','ซิงก์แล้ว '+Math.max(1,Math.round((Date.now()-started)/100)/10)+' วิ.','ข้อมูลในเครื่องและออนไลน์ตรงกันแล้ว');return true}).catch(function(e){clearTimeout(timeout);syncActive=false;syncAttempts++;status('waiting','รอซิงก์ใหม่',e&&e.name==='AbortError'?'การเชื่อมต่อช้า ระบบจะลองใหม่':'ซิงก์ไม่สำเร็จ ระบบจะลองใหม่');if(syncAttempts<=3)schedule([1200,4000,12000][syncAttempts-1]);return false})}
window.ctPersistContent=function(items){var rows=Array.isArray(items)?items:(typeof _ctData!=='undefined'&&Array.isArray(_ctData)?_ctData:loadContentData());if(typeof _ctData!=='undefined')_ctData=rows;if(localSave(rows)){status('local','บันทึกแล้ว','บันทึกในเครื่องแล้ว กำลังรอซิงก์ออนไลน์');schedule(350);return Promise.resolve({local:true,queued:true})}status('syncing','กำลังบันทึกออนไลน์...','พื้นที่ในเครื่องไม่พอ กำลังใช้ฐานข้อมูลออนไลน์แทน');return cloudWriteRows(rows).then(function(){try{localStorage.removeItem(SYNC_PENDING);localStorage.removeItem('rb_olympplus_v1');writeLocalRows(rows)}catch(e){}signalContentUpdated();status('synced','ซิงก์แล้ว','บันทึกลงฐานข้อมูลออนไลน์เรียบร้อย');return {local:false,cloud:true}},function(error){status('waiting','บันทึกไม่สำเร็จ','พื้นที่ในเครื่องไม่พอและยังติดต่อฐานข้อมูลออนไลน์ไม่ได้');throw error})};
window.ctSave=function(items){return window.ctPersistContent(items)};
window.ctSyncNow=function(){clearTimeout(syncTimer);return syncNow(true)};
window.ctMainPage=function(p){window._ctMainPage=Math.max(1,p);if(typeof ctRender==='function')ctRender();var box=document.querySelector('.ct-table-container');if(box)box.scrollIntoView({block:'start',behavior:'smooth'})};
window.ctMainPageSize=function(v){var n=parseInt(v,10);window._ctMainPageSize=[50,100,200].indexOf(n)>=0?n:50;window._ctMainPage=1;try{localStorage.setItem('rb_ct_page_size_v1',String(window._ctMainPageSize));}catch(e){}if(window.rbPageSizeSet)window.rbPageSizeSet('links',window._ctMainPageSize);if(typeof ctRender==='function')ctRender()};
window.ctRenderMainPager=function(total,start,shown,size){var table=document.querySelector('.ct-table-container');if(!table)return;var e=document.getElementById('ct-main-pager');if(!e){e=document.createElement('div');e.id='ct-main-pager';e.className='ct-main-pager';table.insertAdjacentElement('afterend',e)}var pages=Math.max(1,Math.ceil(total/size)),page=Math.min(window._ctMainPage||1,pages),nums=[],from=Math.max(1,page-2),to=Math.min(pages,page+2);for(var i=from;i<=to;i++)nums.push('<button class="ct-main-page '+(i===page?'active':'')+'" onclick="ctMainPage('+i+')">'+i+'</button>');e.innerHTML='<span>แสดง '+(total?start+1:0)+'–'+(start+shown)+' จาก '+total+' รายการ</span><span class="ct-main-pages"><button class="ct-main-page" '+(page<=1?'disabled':'')+' onclick="ctMainPage('+(page-1)+')">‹</button>'+nums.join('')+'<button class="ct-main-page" '+(page>=pages?'disabled':'')+' onclick="ctMainPage('+(page+1)+')">›</button><select class="ct-main-size" onchange="ctMainPageSize(this.value)"><option value="50"'+(size===50?' selected':'')+'>50/หน้า</option><option value="100"'+(size===100?' selected':'')+'>100/หน้า</option><option value="200"'+(size===200?' selected':'')+'>200/หน้า</option></select></span>';status(localStorage.getItem(SYNC_PENDING)?'waiting':'synced',localStorage.getItem(SYNC_PENDING)?'รอซิงก์ใหม่':'ข้อมูลพร้อม')};
window.addEventListener('online',function(){if(localStorage.getItem(SYNC_PENDING))schedule(200)});
window.addEventListener('storage',function(e){if(e.key===SYNC_PENDING&&trackerActive()&&window.rbMultiTab&&window.rbMultiTab.isLeader()){schedule(200);return}if(e.key!=='rb_olympplus_v1'||localStorage.getItem(SYNC_PENDING))return;var items=loadContentData();if(typeof _ctData!=='undefined')_ctData=items;try{window.dispatchEvent(new CustomEvent('rb:content-updated'))}catch(x){}if(trackerActive()&&typeof ctRender==='function')ctRender()});
if(window.addEventListener)window.addEventListener('rb:leader-change',function(e){if(e.detail&&e.detail.leader&&trackerActive()&&localStorage.getItem(SYNC_PENDING))schedule(150)});
document.addEventListener('visibilitychange',function(){if(trackerActive()&&localStorage.getItem(SYNC_PENDING))schedule(300)});
})();
