(function(){
'use strict';
if(window.rbWorkflowOps)return;
var ORD='rb_orders_v1',AUD='rb_ops_audit_v1',SNAP='rb_ops_snapshots_v1',LOCK='rb_ops_locks_v1',TAB=(window.rbMultiTab&&window.rbMultiTab.id)||('tab_'+Math.random().toString(36).slice(2)),MAX_AUDIT=1200,LOCK_TTL=90000;
var modal=null,activeView='inbox',selected={},search='',filter='all',baseVersion='',lockedKey='',lockTimer=null,originalSp=null,hooked=false,auditHydrated=false,auditHydrating=false,cloudBase=typeof FB_DB!=='undefined'?FB_DB:'https://richbiotech-graphic-ads-default-rtdb.firebaseio.com';
function read(key,fallback){try{var value=JSON.parse(localStorage.getItem(key)||'null');return value==null?fallback:value}catch(e){return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(e){return false}}
function orders(){var value=read(ORD,[]);return Array.isArray(value)?value:[]}
function user(){return window._rbUser||{name:localStorage.getItem('rb_cur_user')||'ไม่ระบุ',role:'guest'}}
function clean(value){return JSON.parse(JSON.stringify(value==null?null:value))}
function keyOf(row){return row&&(row._fbKey||row.id)||''}
function same(a,b){try{return JSON.stringify(a)===JSON.stringify(b)}catch(e){return false}}
function changedFields(a,b){var keys={},out=[];Object.keys(a||{}).concat(Object.keys(b||{})).forEach(function(k){if(k!=='_fbKey'&&k!=='_version'&&k!=='updatedAt')keys[k]=1});Object.keys(keys).forEach(function(k){if(!same(a&&a[k],b&&b[k]))out.push(k)});return out}
function auditLoad(){var rows=read(AUD,[]);return Array.isArray(rows)?rows:[]}
function auditSave(rows){write(AUD,(rows||[]).slice(0,MAX_AUDIT))}
function cloud(path,method,data){if(navigator.onLine===false)return Promise.resolve(false);var opt={method:method||'PUT',headers:{'Content-Type':'application/json'}};if(method!=='DELETE')opt.body=JSON.stringify(data||{});return fetch(cloudBase+path+'.json',opt).then(function(r){return r.ok}).catch(function(){return false})}
function hydrateAudit(){if(auditHydrated||auditHydrating||navigator.onLine===false)return;auditHydrating=true;fetch(cloudBase+'/workflow_audit.json').then(function(r){if(!r.ok)throw new Error('audit '+r.status);return r.json()}).then(function(data){var remote=[];if(Array.isArray(data))remote=data.filter(Boolean);else if(data&&typeof data==='object')remote=Object.keys(data).map(function(k){return data[k]}).filter(Boolean);var map={};auditLoad().concat(remote).forEach(function(e){if(e&&e.id&&!map[e.id])map[e.id]=e});auditSave(Object.keys(map).map(function(k){return map[k]}).sort(function(a,b){return(Number(b.ts)||0)-(Number(a.ts)||0)}));auditHydrated=true}).catch(function(){auditHydrated=true}).then(function(){auditHydrating=false;if(modal&&modal.classList.contains('is-open')&&activeView==='timeline')render()})}
function addAudit(action,row,before,fields){var e={id:'evt_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),ts:Date.now(),action:action,orderId:row&&row.id||before&&before.id||'',orderKey:keyOf(row)||keyOf(before),title:row&&(row.title||row.name)||before&&(before.title||before.name)||'',user:user().name||'ไม่ระบุ',role:user().role||'',fields:fields||changedFields(before,row),before:before?clean(before):null,after:row?clean(row):null};var rows=auditLoad();rows.unshift(e);auditSave(rows);cloud('/workflow_audit','POST',e);return e}
function diffAudit(before,after){var oldMap={},newMap={};(before||[]).forEach(function(x){oldMap[keyOf(x)]=x});(after||[]).forEach(function(x){newMap[keyOf(x)]=x});Object.keys(newMap).forEach(function(k){if(!oldMap[k])addAudit('สร้างงาน',newMap[k],null,Object.keys(newMap[k]||{}));else{var fields=changedFields(oldMap[k],newMap[k]);if(fields.length)addAudit('แก้ไขงาน',newMap[k],oldMap[k],fields)}});Object.keys(oldMap).forEach(function(k){if(!newMap[k])addAudit('ลบงาน',null,oldMap[k],[])});}
function fmt(ts){if(!ts)return'-';try{return new Date(ts).toLocaleString('th-TH',{dateStyle:'short',timeStyle:'short'})}catch(e){return new Date(ts).toLocaleString()}}
function statusLabel(k){var m={pending:'มอบหมาย',inprogress:'กำลังดำเนินการ',review:'รอตรวจ',revision:'ต้องแก้ไข',done:'เสร็จสมบูรณ์'};return m[k]||k||'ไม่ระบุ'}
function due(row){if(!row||!row.deadline||row.status==='done')return'ok';var now=new Date();now.setHours(0,0,0,0);var d=new Date(row.deadline);d.setHours(0,0,0,0);var days=Math.round((d-now)/86400000);return days<0?'over':days<=3?'soon':'ok'}
function assigneeCode(name){return window.rbOrderAssigneeCode?window.rbOrderAssigneeCode(name):String(name||'').toUpperCase()}
function visibleOrders(){var rows=orders(),u=user();if(u.role==='graphic'||u.role==='ads'){var c=assigneeCode(u.name);rows=rows.filter(function(x){return x.assignee===c})}return rows}
function isMissing(row){return !row||!(row.title||row.name)||!row.deadline||!row.assignee||!row.type}
function notices(){var rows=visibleOrders(),out=[];rows.forEach(function(o){var d=due(o);if(d==='over')out.push({kind:'danger',title:o.id+' เกิน Deadline',desc:o.title||o.name||'',id:o.id});else if(d==='soon')out.push({kind:'warn',title:o.id+' ใกล้ Deadline',desc:o.title||o.name||'',id:o.id});if(o.status==='revision')out.push({kind:'danger',title:o.id+' ต้องแก้ไข',desc:o.title||o.name||'',id:o.id});if(o.status==='review')out.push({kind:'info',title:o.id+' รอตรวจ',desc:o.title||o.name||'',id:o.id});if(isMissing(o))out.push({kind:'warn',title:o.id+' ข้อมูลยังไม่ครบ',desc:'ตรวจชื่อ ประเภท Deadline และผู้รับผิดชอบ',id:o.id})});return out}
function stageCounts(rows){var c={all:rows.length,new:0,doing:0,review:0,alert:0};rows.forEach(function(o){if(o.status==='pending')c.new++;if(o.status==='inprogress')c.doing++;if(o.status==='review')c.review++;if(o.status==='revision'||due(o)==='over'||isMissing(o))c.alert++});return c}
function snapshots(){var rows=read(SNAP,[]);return Array.isArray(rows)?rows:[]}
function snapshot(label,force){var list=snapshots(),now=Date.now();if(!force&&list[0]&&now-list[0].ts<15*60000)return list[0];var s={id:'snap_'+now,ts:now,label:label||'สำรองอัตโนมัติ',user:user().name||'',orders:clean(orders())};list.unshift(s);write(SNAP,list.slice(0,14));if(user().role==='sup')cloud('/workflow_snapshots/latest','PUT',{id:s.id,ts:s.ts,label:s.label,user:s.user,orders:s.orders});return s}
function dailySnapshot(){var d=new Date(),day=d.getFullYear()+'-'+(d.getMonth()+1)+'-'+d.getDate(),key='rb_ops_snapshot_day_v1';if(localStorage.getItem(key)!==day){snapshot('Snapshot ประจำวัน',true);localStorage.setItem(key,day)}}
function locks(){var l=read(LOCK,{}),now=Date.now(),changed=false;Object.keys(l).forEach(function(k){if(now-(l[k].ts||0)>LOCK_TTL){delete l[k];changed=true}});if(changed)write(LOCK,l);return l}
function lockPath(key){return'/workflow_locks/'+encodeURIComponent(key).replace(/%/g,'_')}
function setLock(key){if(!key)return{ok:true};var l=locks(),existing=l[key],u=user();if(existing&&existing.tab!==TAB)return{ok:false,lock:existing};l[key]={tab:TAB,user:u.name||'ไม่ระบุ',role:u.role||'',ts:Date.now()};write(LOCK,l);lockedKey=key;return{ok:true,lock:l[key]}}
function cloudAcquireLock(key,value,done){if(navigator.onLine===false){done(true,value);return}var url=cloudBase+lockPath(key)+'.json';fetch(url,{headers:{'X-Firebase-ETag':'true'}}).then(function(r){if(!r.ok)throw new Error('lock get '+r.status);var etag=r.headers.get('ETag')||'*';return r.json().then(function(current){return{etag:etag,current:current}})}).then(function(state){var current=state.current;if(current&&current.tab!==TAB&&Date.now()-(Number(current.ts)||0)<=LOCK_TTL){done(false,current);return}return fetch(url,{method:'PUT',headers:{'Content-Type':'application/json','If-Match':state.etag},body:JSON.stringify(value)}).then(function(r){if(r.status===412){done(false,{user:'ผู้ใช้อื่น',ts:Date.now()});return}if(!r.ok)throw new Error('lock put '+r.status);done(true,value)})}).catch(function(){done(true,value)})}
function refreshLock(){if(!lockedKey)return;var l=locks(),value=l[lockedKey];if(!value||value.tab!==TAB)return;value.ts=Date.now();write(LOCK,l);cloud(lockPath(lockedKey),'PUT',value)}
function releaseLock(){if(!lockedKey)return;var l=locks();if(l[lockedKey]&&l[lockedKey].tab===TAB)delete l[lockedKey];write(LOCK,l);cloud('/workflow_locks/'+encodeURIComponent(lockedKey).replace(/%/g,'_'),'DELETE');lockedKey='';clearInterval(lockTimer);lockTimer=null}
function toast(text){var old=document.querySelector('.rb-ops-toast');if(old)old.remove();var t=document.createElement('div');t.className='rb-ops-toast';t.textContent=text;document.body.appendChild(t);setTimeout(function(){t.remove()},3200)}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function canManage(){var r=user().role;return r==='sup'||r==='spec'||r==='audit'}
function ensureButton(){var count=notices().length,panel=document.querySelector('.gsp[data-sub="order"]'),existing=document.getElementById('rb-ops-open');if(existing){var badge=existing.querySelector('.rb-ops-count');if(badge&&badge.textContent!==String(count))badge.textContent=count}else if(panel){var wrap=panel.firstElementChild||panel,button=document.createElement('button');button.type='button';button.id='rb-ops-open';button.innerHTML='<span>▦ ศูนย์งานทีม</span><span class="rb-ops-count">'+count+'</span>';button.onclick=function(){open()};var heading=wrap.querySelector('.rb-section-hero,.rb-graphic-page-header');if(heading)heading.appendChild(button);else{button.style.margin='12px 20px 0';wrap.insertBefore(button,wrap.firstChild)}}var globalBtn=document.getElementById('rb-ops-global-open');if(globalBtn){var globalBadge=globalBtn.querySelector('.rb-ops-count');if(globalBadge&&globalBadge.textContent!==String(count))globalBadge.textContent=count}else if(document.body&&user().role!=='guest'){globalBtn=document.createElement('button');globalBtn.type='button';globalBtn.id='rb-ops-global-open';globalBtn.setAttribute('aria-label','เปิดศูนย์งานทีม');globalBtn.innerHTML='<span>▦ งานของฉัน</span><span class="rb-ops-count">'+count+'</span>';globalBtn.onclick=function(){open()};var sidebar=document.getElementById('sidebar'),footer=sidebar&&sidebar.querySelector('.sb-footer');if(sidebar&&footer)sidebar.insertBefore(globalBtn,footer);else document.body.appendChild(globalBtn)}}
function shell(){if(modal)return modal;modal=document.createElement('div');modal.className='rb-ops-overlay';modal.innerHTML='<section class="rb-ops-shell" role="dialog" aria-modal="true"><header class="rb-ops-head"><span class="rb-ops-head-icon">▦</span><div class="rb-ops-head-copy"><h2>ศูนย์งานทีม</h2><p>งาน แจ้งเตือน ประวัติ Snapshot และสุขภาพระบบในหน้าจอเดียว</p></div><button class="rb-ops-close" type="button" aria-label="ปิด">×</button></header><nav class="rb-ops-tabs"><button class="rb-ops-tab is-active" data-view="inbox">กล่องงานของฉัน</button><button class="rb-ops-tab" data-view="timeline">Timeline</button><button class="rb-ops-tab" data-view="notice">แจ้งเตือน</button><button class="rb-ops-tab" data-view="health">สุขภาพระบบ</button><button class="rb-ops-tab" data-view="snapshot">Snapshot</button></nav><main class="rb-ops-body"><section class="rb-ops-view" data-view="inbox"></section><section class="rb-ops-view" data-view="timeline" hidden></section><section class="rb-ops-view" data-view="notice" hidden></section><section class="rb-ops-view" data-view="health" hidden></section><section class="rb-ops-view" data-view="snapshot" hidden></section></main></section>';document.body.appendChild(modal);modal.querySelector('.rb-ops-close').onclick=close;modal.addEventListener('click',function(e){if(e.target===modal)close();var tab=e.target.closest('.rb-ops-tab');if(tab){activeView=tab.dataset.view;render()}});return modal}
function open(view,orderId){shell();activeView=view||'inbox';modal.classList.add('is-open');document.body.style.overflow='hidden';if(orderId)search=orderId;render()}
function close(){if(modal)modal.classList.remove('is-open');document.body.style.overflow=''}
function cards(rows){var c=stageCounts(rows);return'<div class="rb-ops-cards"><article class="rb-ops-card"><strong>'+c.all+'</strong><span>งานที่มองเห็น</span></article><article class="rb-ops-card"><strong>'+c.new+'</strong><span>งานใหม่</span></article><article class="rb-ops-card"><strong>'+c.doing+'</strong><span>กำลังดำเนินการ</span></article><article class="rb-ops-card is-warn"><strong>'+c.review+'</strong><span>รอตรวจ</span></article><article class="rb-ops-card is-alert"><strong>'+c.alert+'</strong><span>ต้องติดตาม</span></article></div>'}
function filtered(){var rows=visibleOrders(),q=search.toLowerCase();if(q)rows=rows.filter(function(o){return [o.id,o.title,o.name,o.product,o.assignee].join(' ').toLowerCase().indexOf(q)>=0});if(filter==='new')rows=rows.filter(function(o){return o.status==='pending'});if(filter==='doing')rows=rows.filter(function(o){return o.status==='inprogress'});if(filter==='review')rows=rows.filter(function(o){return o.status==='review'});if(filter==='alert')rows=rows.filter(function(o){return o.status==='revision'||due(o)==='over'||isMissing(o)});return rows.sort(function(a,b){var pa=due(a)==='over'?0:a.status==='revision'?1:due(a)==='soon'?2:3,pb=due(b)==='over'?0:b.status==='revision'?1:due(b)==='soon'?2:3;return pa-pb||(a.deadline||'9999').localeCompare(b.deadline||'9999')})}
function inboxHtml(){var rows=filtered(),manage=canManage(),opts='<option value="all">ทั้งหมด</option><option value="new">งานใหม่</option><option value="doing">กำลังทำ</option><option value="review">รอตรวจ</option><option value="alert">ต้องติดตาม</option>';return cards(visibleOrders())+'<div class="rb-ops-toolbar"><input id="rb-ops-search" value="'+esc(search)+'" placeholder="ค้นหาเลขงาน ชื่องาน สินค้า หรือผู้รับผิดชอบ"><select id="rb-ops-filter">'+opts+'</select><button id="rb-ops-clear" type="button">ล้าง</button></div>'+(manage?'<div id="rb-ops-bulk" class="rb-ops-bulk"><strong>เลือก <span id="rb-ops-selected">0</span> งาน</strong><select id="rb-ops-bulk-status"><option value="">เปลี่ยนสถานะ</option><option value="pending">มอบหมาย</option><option value="inprogress">กำลังดำเนินการ</option><option value="review">รอตรวจ</option><option value="revision">ต้องแก้ไข</option><option value="done">เสร็จสมบูรณ์</option></select><select id="rb-ops-bulk-assignee"><option value="">เปลี่ยนผู้รับผิดชอบ</option><option>MOS</option><option>DOM</option><option>TER</option><option>JAM</option><option>NUNE</option><option>BALL</option></select><input id="rb-ops-bulk-date" type="date"><button id="rb-ops-apply" class="rb-ops-action is-primary" type="button">ตรวจสอบและยืนยัน</button></div>':'')+'<div class="rb-ops-table-wrap"><table class="rb-ops-table"><thead><tr>'+(manage?'<th><input id="rb-ops-all" type="checkbox"></th>':'')+'<th>งาน</th><th>ประเภท</th><th>Deadline</th><th>สถานะ</th><th>ผู้รับผิดชอบ</th><th>ความพร้อม</th></tr></thead><tbody>'+rows.map(function(o){return'<tr>'+(manage?'<td><input class="rb-ops-check" type="checkbox" data-key="'+esc(keyOf(o))+'" '+(selected[keyOf(o)]?'checked':'')+'></td>':'')+'<td><button class="rb-ops-name" data-order="'+esc(o.id)+'">'+esc(o.id)+' · '+esc(o.title||o.name||'-')+'</button></td><td>'+esc(o.type||'-')+'</td><td><span class="rb-ops-badge '+due(o)+'">'+esc(o.deadline||'-')+'</span></td><td><span class="rb-ops-badge '+esc(o.status)+'">'+esc(statusLabel(o.status))+'</span></td><td>'+esc(o.assignee||'-')+'</td><td>'+(isMissing(o)?'<span class="rb-ops-badge revision">ข้อมูลไม่ครบ</span>':'<span class="rb-ops-badge done">พร้อม</span>')+'</td></tr>'}).join('')+(rows.length?'':'<tr><td colspan="7" class="rb-ops-empty">ไม่พบรายการงาน</td></tr>')+'</tbody></table></div>'}
function timelineRows(){var detailed=auditLoad(),legacy=read('rb_timeline_v1',[]);if(!Array.isArray(legacy))legacy=[];var mapped=legacy.map(function(e,i){return{id:'legacy_'+(e.ts||i),ts:e.ts||0,action:e.act||'แก้ไขข้อมูล',orderId:e.sec||'ระบบ',title:e.det||'',user:e.user||'',fields:e.as?[e.as]:[],legacy:true}});return detailed.concat(mapped).sort(function(a,b){return(Number(b.ts)||0)-(Number(a.ts)||0)})}
function timelineHtml(){var rows=timelineRows().filter(function(e){var q=search.toLowerCase();return !q||String(e.orderId||'').toLowerCase().indexOf(q)>=0||String(e.title||'').toLowerCase().indexOf(q)>=0||String(e.user||'').toLowerCase().indexOf(q)>=0});return'<div class="rb-ops-toolbar"><input id="rb-ops-event-search" value="'+esc(search)+'" placeholder="ค้นหาเลขงาน หมวดข้อมูล หรือผู้แก้ไข"><button id="rb-ops-event-clear">ล้าง</button></div><div>'+rows.map(function(e){return'<article class="rb-ops-event"><time>'+esc(fmt(e.ts))+'</time><div><b>'+esc(e.action)+' · '+esc(e.orderId)+'</b><span>'+esc(e.title)+' — '+esc(e.user)+'</span><small>'+(e.legacy?'ประวัติจากระบบเดิม':'ช่องที่เปลี่ยน: '+esc((e.fields||[]).join(', ')||'-'))+'</small></div>'+(!e.legacy&&e.before&&user().role==='sup'?'<button class="rb-ops-action" data-restore-event="'+esc(e.id)+'">ย้อนคืนรายการนี้</button>':'')+'</article>'}).join('')+(rows.length?'':'<div class="rb-ops-empty">ยังไม่มีประวัติการแก้ไข</div>')+'</div>'}
function noticeHtml(){var rows=notices();return'<div>'+rows.map(function(n){return'<button class="rb-ops-notice is-'+esc(n.kind)+'" data-order="'+esc(n.id)+'" type="button"><i></i><span><strong>'+esc(n.title)+'</strong><small>'+esc(n.desc)+'</small></span></button>'}).join('')+(rows.length?'':'<div class="rb-ops-empty">ไม่มีรายการที่ต้องแจ้งเตือน</div>')+'</div>'}
function healthData(){var rows=orders(),queue=read('rb_order_write_queue_v1',[]),dupes={},duplicate=0;rows.forEach(function(o){var k=keyOf(o);if(dupes[k])duplicate++;dupes[k]=1});var invalid=rows.filter(isMissing).length,sync=document.getElementById('rb-sync-chip'),state=sync&&sync.getAttribute('data-state')||'unknown';return[{name:'การเชื่อมต่อ',value:navigator.onLine===false?'ออฟไลน์':'ออนไลน์',state:navigator.onLine===false?'bad':'good'},{name:'สถานะซิงค์',value:state,state:state==='error'?'bad':state==='waiting'?'warn':'good'},{name:'คิวรอบันทึก',value:(queue&&queue.length||0)+' รายการ',state:queue&&queue.length?'warn':'good'},{name:'ข้อมูลงาน',value:rows.length+' รายการ',state:rows.length?'good':'warn'},{name:'ข้อมูลไม่ครบ',value:invalid+' รายการ',state:invalid?'warn':'good'},{name:'คีย์ซ้ำ',value:duplicate+' รายการ',state:duplicate?'bad':'good'}]}
function healthHtml(){return'<div class="rb-ops-health-grid">'+healthData().map(function(h){return'<article class="rb-ops-health is-'+h.state+'"><strong>'+esc(h.name)+'</strong><span>'+esc(h.value)+'</span></article>'}).join('')+'</div><div class="rb-ops-toolbar" style="margin-top:14px"><button id="rb-ops-retry" class="is-primary">ลองซิงค์รายการค้างอีกครั้ง</button><button id="rb-ops-export">ส่งออกรายงานวินิจฉัย</button></div>'}
function snapshotHtml(){var list=snapshots(),manage=user().role==='sup';return'<div class="rb-ops-toolbar">'+(manage?'<button id="rb-ops-snapshot-now" class="is-primary">สร้าง Snapshot ตอนนี้</button>':'<span>เฉพาะ Supervisor ที่สร้างหรือกู้คืน Snapshot ได้</span>')+'</div><div>'+list.map(function(s){return'<article class="rb-ops-snapshot"><div><strong>'+esc(s.label)+'</strong><small>'+esc(fmt(s.ts))+' · '+esc(s.user||'-')+' · '+(s.orders||[]).length+' งาน</small></div>'+(manage?'<button class="rb-ops-action" data-restore-snapshot="'+esc(s.id)+'">กู้คืน</button>':'')+'</article>'}).join('')+(list.length?'':'<div class="rb-ops-empty">ยังไม่มี Snapshot</div>')+'</div>'}
function render(){if(!modal)return;if(activeView==='timeline')hydrateAudit();modal.querySelectorAll('.rb-ops-tab').forEach(function(b){b.classList.toggle('is-active',b.dataset.view===activeView)});modal.querySelectorAll('.rb-ops-view').forEach(function(v){v.hidden=v.dataset.view!==activeView});var view=modal.querySelector('.rb-ops-view[data-view="'+activeView+'"]');view.innerHTML=activeView==='inbox'?inboxHtml():activeView==='timeline'?timelineHtml():activeView==='notice'?noticeHtml():activeView==='health'?healthHtml():snapshotHtml();bindView(view)}
function bindView(view){var q=view.querySelector('#rb-ops-search');if(q)q.oninput=function(){search=this.value;render()};var f=view.querySelector('#rb-ops-filter');if(f){f.value=filter;f.onchange=function(){filter=this.value;render()}}var clear=view.querySelector('#rb-ops-clear');if(clear)clear.onclick=function(){search='';filter='all';selected={};render()};var eq=view.querySelector('#rb-ops-event-search');if(eq)eq.oninput=function(){search=this.value;render()};var ec=view.querySelector('#rb-ops-event-clear');if(ec)ec.onclick=function(){search='';render()};view.querySelectorAll('[data-order]').forEach(function(b){b.onclick=function(){var id=this.dataset.order;close();if(typeof window.openOM==='function')window.openOM(id);else if(typeof window.gsOrdModal==='function')window.gsOrdModal(id)}});view.querySelectorAll('.rb-ops-check').forEach(function(c){c.onchange=function(){selected[this.dataset.key]=this.checked;updateBulk(view)}});var all=view.querySelector('#rb-ops-all');if(all)all.onchange=function(){view.querySelectorAll('.rb-ops-check').forEach(function(c){c.checked=all.checked;selected[c.dataset.key]=all.checked});updateBulk(view)};var apply=view.querySelector('#rb-ops-apply');if(apply)apply.onclick=bulkApply;view.querySelectorAll('[data-restore-event]').forEach(function(b){b.onclick=function(){restoreEvent(this.dataset.restoreEvent)}});view.querySelectorAll('[data-restore-snapshot]').forEach(function(b){b.onclick=function(){restoreSnapshot(this.dataset.restoreSnapshot)}});var sn=view.querySelector('#rb-ops-snapshot-now');if(sn)sn.onclick=function(){snapshot('Snapshot โดย '+user().name,true);toast('สร้าง Snapshot แล้ว');render()};var retry=view.querySelector('#rb-ops-retry');if(retry)retry.onclick=function(){if(window.fbFlushOrderQueue)window.fbFlushOrderQueue();if(window.fbRefreshOrders)window.fbRefreshOrders();toast('เริ่มตรวจและซิงค์รายการค้างแล้ว');setTimeout(render,500)};var exp=view.querySelector('#rb-ops-export');if(exp)exp.onclick=exportHealth;updateBulk(view)}
function updateBulk(view){var count=Object.keys(selected).filter(function(k){return selected[k]}).length,bar=view.querySelector('#rb-ops-bulk'),span=view.querySelector('#rb-ops-selected');if(span)span.textContent=count;if(bar)bar.classList.toggle('is-visible',count>0)}
function bulkApply(){var keys=Object.keys(selected).filter(function(k){return selected[k]}),st=document.getElementById('rb-ops-bulk-status').value,as=document.getElementById('rb-ops-bulk-assignee').value,dt=document.getElementById('rb-ops-bulk-date').value;if(!keys.length||(!st&&!as&&!dt)){toast('เลือกงานและข้อมูลที่จะเปลี่ยนก่อน');return}if(!confirm('ยืนยันแก้ไข '+keys.length+' งานพร้อมกัน? ระบบจะสร้าง Snapshot ก่อนดำเนินการ'))return;snapshot('ก่อนแก้ไขหลายรายการ',true);var rows=orders();rows.forEach(function(o){if(keys.indexOf(keyOf(o))<0)return;if(st)o.status=st;if(as)o.assignee=as;if(dt)o.deadline=dt;o.updatedAt=Date.now();o._updatedBy=user().name});window.spORD(rows);selected={};toast('อัปเดต '+keys.length+' งานแล้ว');render()}
function restoreEvent(id){var e=auditLoad().find(function(x){return x.id===id});if(!e||!e.before)return;if(!confirm('ย้อนคืน '+e.orderId+' เป็นข้อมูลก่อนการแก้ไขครั้งนี้?'))return;snapshot('ก่อนย้อนคืน '+e.orderId,true);var rows=orders(),idx=rows.findIndex(function(o){return keyOf(o)===e.orderKey||o.id===e.orderId});if(idx>=0)rows[idx]=clean(e.before);else rows.unshift(clean(e.before));window.spORD(rows);toast('ย้อนคืน '+e.orderId+' แล้ว');render()}
function restoreSnapshot(id){var s=snapshots().find(function(x){return x.id===id});if(!s||!Array.isArray(s.orders))return;if(!confirm('กู้คืน Snapshot '+fmt(s.ts)+'? ระบบจะสำรองข้อมูลปัจจุบันไว้อีกชุดก่อน'))return;snapshot('ก่อนกู้คืน Snapshot',true);window.spORD(clean(s.orders));toast('กู้คืน Snapshot แล้ว');render()}
function exportHealth(){var payload={createdAt:new Date().toISOString(),user:user(),health:healthData(),queue:read('rb_order_write_queue_v1',[]),counts:stageCounts(orders())},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='richbiotech-system-health-'+Date.now()+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function modalOrder(){var root=document.getElementById('rb-order-modal');if(!root||getComputedStyle(root).display==='none')return null;var id=(document.getElementById('om-id')&&document.getElementById('om-id').textContent||'').trim();return orders().find(function(o){return o.id===id})||{id:id}}
function blockModal(root,lock){var b=document.createElement('div');b.className='rb-ops-lock-banner';b.textContent=(lock&&lock.user||'ผู้ใช้อื่น')+' กำลังแก้ไขงานนี้อยู่ กรุณารอหรือเปิดดูแบบอ่านอย่างเดียว';var tabs=root.querySelector('.rb-om-tabs,.rb-om-tabbar');if(tabs)tabs.insertAdjacentElement('afterend',b);root.setAttribute('data-rb-locked','1');root.removeAttribute('data-rb-lock-checking');root.querySelectorAll('input,select,textarea,button').forEach(function(el){if(!el.classList.contains('rb-om-close')&&!/ปิด/.test(el.textContent||''))el.disabled=true})}
function lockModal(){var root=document.getElementById('rb-order-modal'),row=modalOrder();if(!root||!row||!row.id)return;root.querySelectorAll('.rb-ops-lock-banner').forEach(function(x){x.remove()});root.setAttribute('data-rb-lock-checking','1');var result=setLock(keyOf(row)||row.id);baseVersion=String((orders().find(function(o){return o.id===row.id})||{})._version||0);if(!result.ok){blockModal(root,result.lock);return}cloudAcquireLock(keyOf(row)||row.id,result.lock,function(ok,remote){if(!root.isConnected)return;if(!ok){blockModal(root,remote);return}root.removeAttribute('data-rb-lock-checking');root.removeAttribute('data-rb-locked');clearInterval(lockTimer);lockTimer=setInterval(refreshLock,20000)})}
function validateModal(button){var root=document.getElementById('rb-order-modal');if(!root||getComputedStyle(root).display==='none')return true;if(root.getAttribute('data-rb-locked')==='1'){toast('งานนี้กำลังถูกแก้ไขจากอีกหน้าต่าง');return false}if(root.getAttribute('data-rb-lock-checking')==='1'){toast('กำลังตรวจสอบผู้ที่แก้ไขงาน กรุณารอสักครู่');return false}root.querySelectorAll('.rb-ops-complete-banner').forEach(function(x){x.remove()});root.querySelectorAll('.rb-ops-field-error').forEach(function(x){x.classList.remove('rb-ops-field-error')});var text=(button&&button.textContent||'').trim();if(!/(สั่งงาน|บันทึก|ส่งตรวจอีกครั้ง)/.test(text)||/บันทึกการติดตาม/.test(text))return true;var fields=[['om-name','ชื่องาน'],['om-type','ประเภทงาน'],['om-dl','Deadline'],['om-mb','ผู้รับผิดชอบ']],missing=[];fields.forEach(function(pair){var el=document.getElementById(pair[0]);if(el&&!String(el.value||'').trim()){missing.push(pair[1]);el.classList.add('rb-ops-field-error')}});var current=modalOrder(),version=String((orders().find(function(o){return current&&o.id===current.id})||{})._version||0);if(baseVersion&&version!==baseVersion){missing.push('ข้อมูลถูกแก้จากอีกหน้าต่าง กรุณาปิดและเปิดงานใหม่')}if(!missing.length)return true;var banner=document.createElement('div');banner.className='rb-ops-complete-banner';banner.textContent='ตรวจพบข้อมูลที่ต้องแก้ก่อนบันทึก: '+missing.join(', ');var tabs=root.querySelector('.rb-om-tabs,.rb-om-tabbar');if(tabs)tabs.insertAdjacentElement('afterend',banner);var first=root.querySelector('.rb-ops-field-error');if(first)first.focus();return false}
function hookSp(){if(hooked||typeof window.spORD!=='function')return;hooked=true;originalSp=window.spORD;window.spORD=function(next){var before=orders();snapshot('สำรองก่อนบันทึก',false);var rows=Array.isArray(next)?next:[];rows.forEach(function(row){var old=before.find(function(x){return keyOf(x)===keyOf(row)||x.id===row.id});if(!old||changedFields(old,row).length){row._version=(Number(old&&old._version)||0)+1;row._updatedBy=user().name||''}});diffAudit(before,rows);var result=originalSp.call(window,rows);ensureButton();if(modal&&modal.classList.contains('is-open'))render();return result}}
document.addEventListener('click',function(e){var button=e.target.closest('button');if(button&&button.closest('#rb-order-modal')&&e.eventPhase!==0){if(!validateModal(button)){e.preventDefault();e.stopImmediatePropagation();return}}if(button&&/ปิด/.test(button.textContent||'')&&button.closest('#rb-order-modal'))releaseLock()},true);
window.addEventListener('storage',function(e){if(e.key===ORD||e.key===AUD||e.key===LOCK){ensureButton();if(modal&&modal.classList.contains('is-open'))render()}});window.addEventListener('pagehide',releaseLock);window.addEventListener('online',function(){if(window.fbFlushOrderQueue)window.fbFlushOrderQueue()});
new MutationObserver(function(){hookSp();ensureButton();var root=document.getElementById('rb-order-modal');if(root&&getComputedStyle(root).display!=='none'&&!root.getAttribute('data-rb-lock-ready')){root.setAttribute('data-rb-lock-ready','1');setTimeout(lockModal,0)}if(root&&getComputedStyle(root).display==='none'&&root.getAttribute('data-rb-lock-ready')){root.removeAttribute('data-rb-lock-ready');releaseLock()}}).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['style','class']});
dailySnapshot();setTimeout(function(){hookSp();ensureButton()},120);setInterval(ensureButton,3000);
window.rbWorkflowOps={open:open,close:close,snapshot:snapshot,health:healthData,notifications:notices};
window._rbWorkflowOpsTest={changedFields:changedFields,isMissing:isMissing,due:due,stageCounts:stageCounts,keyOf:keyOf};
})();
