const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {installSecureAuthMock}=require('./secure-auth-mock');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.RB_TEST_BROWSER_CHANNEL||'chrome'});try{
const root=path.resolve(__dirname,'../..'),origin='http://127.0.0.1:8014',manual={},errors=[];let writes=0;
for(let i=1;i<=3;i++){const id='inline_'+i,at=new Date(2026,8,12+i).getTime();manual[id]={id,ref:id,ruleId:'sheet_import',employee:'JAM',title:'ไม่เคลียร์ตารางสรุปแอด '+i,amount:50,detectedAt:at,dueAt:at,period:'2026-09',sourceStatus:'หักเงินแล้ว',evidence:'https://example.test/evidence/'+i,sourceEvidence:{url:'https://example.test/evidence/'+i,checkedAt:Date.now()}}}
manual.other={...manual.inline_1,id:'other',employee:'DOM'};
for(const x of Object.values(manual)){const d=new Date(x.detectedAt),date=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');x.sourceEvidence={...x.sourceEvidence,identity:[date,x.period,x.employee,x.title,date,50,''].join('|')}}
async function device(role,name){const ctx=await browser.newContext({viewport:{width:1280,height:900}});await ctx.route('**/*',route=>{const u=new URL(route.request().url()),file=path.resolve(root,'.'+u.pathname);return u.origin===origin&&file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort()});await installSecureAuthMock(ctx,{role,name});await ctx.route(/firebaseio\.com\/workflow_audit\/deductions_v1(?:\/[^?]+)?\.json/,route=>{if(route.request().method()!=='GET')writes++;return route.fulfill({json:{manual}})});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window._rbUser?.name);await page.locator('#sidebar button').filter({hasText:'Graphic'}).click();await page.getByRole('button',{name:'ยอดหักออดิต',exact:true}).click();await page.locator('#adc-app .adc-sync-info').first().waitFor();await page.locator('[data-period]').fill('2026-09');await page.locator('[data-period]').dispatchEvent('change');return {page,ctx}}
async function inline(page,id){await page.locator('[data-item="'+id+'"]').click();assert.equal(await page.locator('[data-ledger-detail]').count(),1);assert.equal(await page.locator('[data-ledger-detail]').evaluate(el=>el.previousElementSibling.dataset.ledgerItem),id);assert.equal(await page.locator('#adc-app>.adc-detail').count(),0);assert.equal(await page.locator('[data-item="'+id+'"]').getAttribute('aria-expanded'),'true');assert.equal(await page.getByRole('link',{name:'เปิดหลักฐาน',exact:true}).getAttribute('href'),'https://example.test/evidence/'+id.replace('inline_',''));}
const supervisor=await device('sup','View'),p=supervisor.page;await p.locator('#adc-app select[data-employee]').selectOption('JAM');await inline(p,'inline_2');assert.equal(await p.locator('[data-ledger-detail]').evaluate(el=>el.nextElementSibling?.dataset.ledgerItem),'inline_3');
await inline(p,'inline_1');await p.evaluate(()=>window._rbAuditDeductionRefresh());assert.equal(await p.locator('[data-ledger-detail]').evaluate(el=>el.previousElementSibling.dataset.ledgerItem),'inline_1');await p.locator('[data-item="inline_1"]').click();assert.equal(await p.locator('[data-ledger-detail]').count(),0);
await inline(p,'inline_2');await p.locator('[data-close-detail]').click();assert.equal(await p.locator('[data-ledger-detail]').count(),0);assert.equal(await p.evaluate(()=>document.activeElement.dataset.item),'inline_2');
await inline(p,'inline_2');await p.locator('[data-source]').selectOption('orders');assert.equal(await p.locator('[data-ledger-detail]').count(),0);await p.locator('[data-source]').selectOption('ALL');await inline(p,'inline_2');
await p.locator('[data-ledger-item="inline_2"]').evaluate(el=>el.scrollIntoView({block:"center"}));await p.screenshot({path:path.resolve(root,'../audit-inline474-desktop.png')});
await p.setViewportSize({width:390,height:844});await p.locator('[data-ledger-item="inline_2"]').evaluate(el=>el.scrollIntoView({block:"center"}));assert.equal(await p.locator('.adc-table-wrap').evaluate(el=>el.scrollWidth<=el.clientWidth+2),true,'mobile detail must fit table width');await p.screenshot({path:path.resolve(root,'../audit-inline474-mobile.png')});await p.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));assert.equal(await p.locator('[data-ledger-detail]').isVisible(),true);
await p.locator('[data-view]').selectOption('audit');assert.equal(await p.locator('[data-ledger-detail]').count(),0);assert.equal(await p.locator('.adc-workbench>.adc-detail').count(),1,'audit workbench keeps its existing layout');
const staff=await device('graphic','JAM');await inline(staff.page,'inline_2');assert.equal(await staff.page.locator('[data-item="other"]').count(),0);assert.equal(await staff.page.getByRole('link',{name:'ดูรายการต้นทาง',exact:true}).count(),0);assert.equal(await staff.page.getByRole('button',{name:'＋ เพิ่มยอดหัก',exact:true}).count(),0);assert.equal(await staff.page.getByRole('button',{name:'ลบรายการหัก',exact:true}).count(),0);
await staff.ctx.setOffline(true);await inline(staff.page,'inline_3');await staff.page.locator('[data-close-detail]').click();assert.equal(await staff.page.locator('[data-ledger-detail]').count(),0);
for(let i=4;i<=53;i++){const id='inline_'+i,at=new Date(2026,8,16,0,0,i).getTime();manual[id]={...manual.inline_1,id,ref:id,title:'รายการแบ่งหน้า '+i,detectedAt:at,dueAt:at,evidence:'https://example.test/evidence/'+i,sourceEvidence:{url:'https://example.test/evidence/'+i,checkedAt:Date.now(),identity:['2026-09-16','2026-09','JAM','รายการแบ่งหน้า '+i,'2026-09-16',50,''].join('|')}}}
const dense=await device('graphic','JAM');await dense.page.locator('#adc-app .rbps-pager [aria-label="หน้าถัดไป"]').click();await dense.page.waitForFunction(()=>!document.querySelector('[data-ledger-item="inline_51"]').hidden);await inline(dense.page,'inline_51');await dense.page.waitForTimeout(120);assert.equal(await dense.page.locator('#adc-app .rbps-pager [aria-current="page"]').innerText(),'2');assert.match(await dense.page.locator('#adc-app .rbps-summary').innerText(),/51–53.*53/);assert.equal(await dense.page.locator('[data-ledger-detail]').isVisible(),true);await dense.page.locator('#adc-app .rbps-pager [aria-label="หน้าก่อนหน้า"]').click();assert.equal(await dense.page.locator('[data-ledger-detail]').isVisible(),false,'detail follows hidden owner when changing page');await dense.page.locator('#adc-app .rbps-pager [aria-label="หน้าถัดไป"]').click();assert.equal(await dense.page.locator('[data-ledger-detail]').isVisible(),true);await dense.page.locator('[data-close-detail]').click();await dense.page.waitForTimeout(120);assert.equal(await dense.page.locator('#adc-app .rbps-pager [aria-current="page"]').innerText(),'2');
assert.equal(writes,0,'display controls must not change financial data');assert.deepEqual(errors,[]);console.log('PASS inline position, switch/collapse/focus, refresh/filter, evidence, mobile/dark, staff permissions, offline viewing and unchanged audit workbench; 53-row pagination excludes details and preserves page 2');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
