const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {installSecureAuthMock}=require('./secure-auth-mock');const {workbook,employees}=require('../helpers/audit-sheet-workbook.cjs');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.RB_TEST_BROWSER_CHANNEL||'chrome'});try{
 const root=path.resolve(__dirname,'../..'),origin='http://127.0.0.1:8014',db={sheetImports:{},decisions:{},manual:{}};let sheetOptions={},sheetOffline=false,failWrite=false,loseAck=false,loseCreateAck=false,writes=0;const errors=[];
 for(const day of [12,15])for(const employee of employees){const id=`legacy_${day}_${employee}`,at=new Date(2026,8,day).getTime();db.sheetImports[id]={id,ref:id,ruleId:'sheet_import',employee,title:'ไม่เคลียร์ตารางสรุปแอด',ruleName:'ไม่เคลียร์ตารางสรุปแอด',detectedAt:at,dueAt:at,amount:850,period:'2026-09',evidence:`รูปตรวจวันที่ ${day}/09/69`,note:'',sourceStatus:'รอตรวจสอบ',sheetSignature:'original '+id};db.decisions[id]={status:'waived',reason:'ประวัติเดิม',at:Date.now()}}
 const original=JSON.stringify(db);
 async function device(role='sup',name='View'){
  const ctx=await browser.newContext();await ctx.route('**/*',route=>{const u=new URL(route.request().url()),file=path.resolve(root,'.'+u.pathname);return u.origin===origin&&file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort()});await installSecureAuthMock(ctx,{role,name});
  await ctx.route(/docs\.google\.com\/spreadsheets\/d\/16tMM.*\/export\?/,route=>sheetOffline?route.abort():route.fulfill({status:200,headers:{'access-control-allow-origin':'*'},contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',body:workbook(sheetOptions)}));
  await ctx.route(/firebaseio\.com\/workflow_audit\/deductions_v1(?:\/[^?]+)?\.json/,route=>{const req=route.request(),parts=new URL(req.url()).pathname.replace(/\.json$/,'').split('/').slice(3);let val=db;for(const p of parts)val=val?.[p];const etag=val==null?'null_etag':'"'+Buffer.from(JSON.stringify(val)).toString('base64').slice(-32)+'"';
   if(req.method()==='GET')return route.fulfill({json:val??null,headers:{ETag:etag,'access-control-allow-origin':'*','access-control-expose-headers':'ETag'}});
   assert(['sup','audit'].includes(role),'staff must never repair/write central evidence');assert.equal(req.method(),'PUT');assert(parts[0]==='sheetImports'&&(parts.length===2||parts.length===3&&parts[2]==='sourceEvidence'),'never replace ledger/financial/history data');
   if(failWrite){failWrite=false;return route.fulfill({status:503,json:{error:'offline'}})}if(req.headers()['if-match']!==etag)return route.fulfill({status:412,json:{error:'conflict'}});
   let parent=db;for(const p of parts.slice(0,-1))parent=parent[p]??={};parent[parts.at(-1)]=req.postDataJSON();writes++;if(loseAck||loseCreateAck&&parts.length===2){loseAck=false;loseCreateAck=false;return route.abort('failed')}return route.fulfill({json:parent[parts.at(-1)]});
  });
  const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window._rbUser?.name);await page.locator('#sidebar button').filter({hasText:'Graphic'}).click();await page.getByRole('button',{name:'ยอดหักออดิต',exact:true}).click();if(role==='sup')await page.locator('[data-view]').selectOption('audit');return {page,ctx};
 }
 async function sync(d){await d.page.waitForFunction(()=>!!document.querySelector('[data-action="sheet"]'));await d.page.locator('[data-action="sheet"]').click();await d.page.getByText(/ยืนยันออนไลน์แล้ว|ยังซิงก์ไม่ครบ/).waitFor();return d.page.locator('.adc-toast').innerText()}
 const a=await device();await a.page.waitForFunction(()=>document.querySelector('[data-item="legacy_12_JAM"]'));await a.page.locator('[data-item="legacy_12_JAM"]').first().click();await a.page.getByRole('link',{name:'เปิดหลักฐาน',exact:false}).waitFor();assert.equal(await a.page.getByRole('link',{name:'เปิดหลักฐาน',exact:false}).getAttribute('href'),'https://example.test/evidence/12/JAM');await sync(a);assert.equal(Object.keys(db.sheetImports).length,12);
 const repaired=JSON.parse(JSON.stringify(db));for(const x of Object.values(repaired.sheetImports))delete x.sourceEvidence;assert.equal(JSON.stringify(repaired),original,'repair preserves every legacy value and decision');
 for(const [id,x] of Object.entries(db.sheetImports)){await a.page.locator(`[data-item="${id}"]`).first().click();assert.equal(await a.page.getByRole('link',{name:'เปิดหลักฐาน',exact:false}).getAttribute('href'),x.sourceEvidence.url);assert(decodeURIComponent(await a.page.getByRole('link',{name:'ดูรายการต้นทาง',exact:false}).getAttribute('href')).includes("'บันทึกออดิต'!A"))}
 const beforeStaff=writes,b=await device('graphic','JAM');await b.page.getByRole('button',{name:/ดูรายละเอียด JAM/}).first().click();await b.page.getByRole('link',{name:'เปิดหลักฐาน',exact:false}).waitFor();assert.equal(writes,beforeStaff);assert.equal(await b.page.locator('[data-action="sheet"]').count(),0);assert.equal(await b.page.locator('[data-item*="DOM"]').count(),0);
 await a.page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('full','QuotaExceededError')}});
 sheetOptions={changed:true};assert((await sync(a)).includes('ยืนยันออนไลน์แล้ว'));assert.equal(Object.keys(db.sheetImports).length,12);assert(Object.values(db.sheetImports).every(x=>x.sourceEvidence.url.endsWith('/corrected')));await b.page.reload();await b.page.waitForFunction(()=>window._rbUser?.name);await b.page.locator('#sidebar button').filter({hasText:'Graphic'}).click();await b.page.getByRole('button',{name:'ยอดหักออดิต',exact:true}).click();await b.page.getByRole('button',{name:/ดูรายละเอียด JAM/}).first().click();await b.page.waitForFunction(()=>document.querySelector('.adc-sheet-source-link')?.href.endsWith('/corrected'));
 sheetOffline=true;assert((await sync(a)).includes('ยังซิงก์ไม่ครบ'));assert.equal(Object.keys(db.sheetImports).length,12);sheetOffline=false;
 sheetOptions={changed:false};failWrite=true;assert((await sync(a)).includes('ยังซิงก์ไม่ครบ'));assert((await sync(a)).includes('ยืนยันออนไลน์แล้ว'));
 sheetOptions={changed:true};loseAck=true;assert((await sync(a)).includes('ยังซิงก์ไม่ครบ'));assert((await sync(a)).includes('ยืนยันออนไลน์แล้ว'));assert.equal(Object.keys(db.sheetImports).length,12);sheetOptions={changed:true,extra:true};loseCreateAck=true;assert((await sync(a)).includes('ยังซิงก์ไม่ครบ'));assert.equal(Object.keys(db.sheetImports).length,13);await sync(a);assert.equal(Object.keys(db.sheetImports).length,13);
 const c=await device('audit','Audit');await Promise.all([sync(a),sync(c)]);assert.equal(Object.keys(db.sheetImports).length,13);
 await a.page.locator('[data-item="legacy_12_JAM"]').first().click();await a.page.screenshot({path:path.resolve(root,'../audit-evidence470-preview.png'),fullPage:false});assert.deepEqual(errors,[]);console.log('PASS all 12 links/source rows, legacy IDs/history/amounts, changed-link dedupe, separate employee context, offline/partial-write/lost-ack retry and new-row append');
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
