const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');const {installSecureAuthMock}=require('./secure-auth-mock');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.RB_TEST_BROWSER_CHANNEL||'chrome'});try{const root=path.resolve(__dirname,'../..'),origin='http://127.0.0.1:8014',entry={id:'qa_charge',ruleId:'order_not_submitted',ref:'GR_QA',orderId:'GR_QA',employee:'JAM',title:'GR_QA · ทดสอบยอดหัก',amount:10,detectedAt:new Date(2026,8,14,12).getTime(),dueAt:new Date(2026,8,14,12).getTime(),period:'2026-09',autoDeadlineCharge:true};let ledger={},lostAck=false,loseNext=false,writes=0;const errors=[];
async function device(role='sup',name='View'){const ctx=await browser.newContext();await ctx.route('**/*',route=>{const u=new URL(route.request().url()),file=path.resolve(root,'.'+u.pathname);return u.origin===origin&&file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort()});await installSecureAuthMock(ctx,{role,name});await ctx.route(/firebaseio\.com\/workflow_audit\/deductions_v1\.json/,route=>route.fulfill({json:{manual:{qa_charge:entry}}}));await ctx.route(/firebaseio\.com\/audit_deduction_adjustments_v1(?:\/[^?]+)?\.json/,async route=>{const req=route.request(),parts=new URL(req.url()).pathname.replace(/\.json$/,'').split('/').filter(Boolean).slice(1);if(req.method()==='GET'){if(lostAck){lostAck=false;return route.abort('failed')}return route.fulfill({json:parts.length===0?ledger:parts.length===1?(ledger[parts[0]]||null):(ledger[parts[0]]||{})[parts[1]]||null})}assert.equal(req.method(),'PUT');assert.equal(parts.length,2);assert.equal(req.headers()['if-match'],'null_etag');if((ledger[parts[0]]||{})[parts[1]])return route.fulfill({status:412,json:{error:'exists'}});const data=req.postDataJSON();assert.equal(data.actorUid,'qa-secure-user');ledger[parts[0]]??={};ledger[parts[0]][parts[1]]={...data,at:Date.now()};writes++;if(loseNext){loseNext=false;lostAck=true}return route.fulfill({json:ledger[parts[0]][parts[1]]})});const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/index.html',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window._rbUser?.name);await page.locator('#sidebar button').filter({hasText:'Graphic'}).click();await page.getByRole('button',{name:'ยอดหักออดิต',exact:true}).click();if(role==='sup')await page.locator('[data-view]').selectOption('audit');if(role==='graphic'){await page.locator('[data-status]').selectOption('removed');await page.locator('[data-item="qa_charge"]').first().click()}else{await page.getByRole('button',{name:/JAM.*ทดสอบยอดหัก/}).click()}await page.locator('.adc-adjust-total').waitFor();return {ctx,page}}
const a=await device(),b=await device('audit','Audit');assert((await a.page.locator('.adc-adjust-total').innerText()).includes('฿10'));
async function openAdd(d,n,reason){await d.page.getByRole('button',{name:'＋ เพิ่มยอดหัก',exact:true}).click();await d.page.locator('#adc-adjust-dialog input[name="amount"]').fill(String(n));await d.page.locator('#adc-adjust-dialog textarea').fill(reason)}
async function save(d){await d.page.locator('#adc-adjust-dialog [type="submit"]').click()}
await openAdd(a,20,'ผลตรวจครั้งแรก');await a.ctx.setOffline(true);await save(a);await a.page.getByText('ยังออฟไลน์ ข้อมูลที่กรอกยังอยู่ กรุณาเชื่อมต่อแล้วบันทึกอีกครั้ง').waitFor();assert.equal(writes,0);assert.equal(await a.page.locator('#adc-adjust-dialog textarea').inputValue(),'ผลตรวจครั้งแรก');await a.ctx.setOffline(false);await save(a);await a.page.locator('#adc-adjust-dialog').waitFor({state:'detached'});assert.equal(writes,1);assert.equal(await a.page.locator('.adc-adjust-total strong').innerText(),'฿30');
await b.page.evaluate(()=>window.rbAuditAdjustments.reload());assert.equal(await b.page.locator('.adc-adjust-total strong').innerText(),'฿30');await openAdd(b,5,'เพิ่มพร้อมกัน');await openAdd(a,10,'เพิ่มจากอีกเครื่อง');await save(a);await a.page.locator('#adc-adjust-dialog').waitFor({state:'detached'});await save(b);await b.page.getByText('ยอดมีการเปลี่ยนแปลงจากอีกเครื่อง ตรวจยอดใหม่แล้วกดบันทึกอีกครั้ง').waitFor();assert.equal(writes,2);await save(b);await b.page.locator('#adc-adjust-dialog').waitFor({state:'detached'});assert.equal(await b.page.locator('.adc-adjust-total strong').innerText(),'฿45');
await openAdd(b,5,'ทดสอบตอบกลับหาย');loseNext=true;await save(b);await b.page.locator('#adc-adjust-dialog [type="submit"]:not([disabled])').waitFor();assert.equal(writes,4);await save(b);await b.page.locator('#adc-adjust-dialog').waitFor({state:'detached'});assert.equal(writes,4,'retry must not double charge');assert.equal(await b.page.locator('.adc-adjust-total strong').innerText(),'฿50');
await b.page.getByRole('button',{name:'ลบรายการหัก',exact:true}).click();await b.page.locator('#adc-adjust-dialog textarea').fill('ยกเลิกรายการตัวอย่าง');await save(b);await b.page.locator('#adc-adjust-dialog').waitFor({state:'detached'});await b.page.locator('[data-status]').selectOption('removed');await b.page.getByRole('button',{name:/JAM.*ทดสอบยอดหัก/}).click();assert.equal(await b.page.locator('.adc-adjust-total strong').innerText(),'฿0');assert.equal(await b.page.locator('.adc-adjust-history article').count(),5);assert.equal(await b.page.getByRole('button',{name:'＋ เพิ่มยอดหัก',exact:true}).count(),0);await b.page.reload({waitUntil:'domcontentloaded'});await b.page.waitForFunction(()=>window.rbAuditAdjustments?.removed({id:'qa_charge',ruleId:'order_not_submitted'}));assert.equal(await b.page.evaluate(()=>window.rbAuditAdjustments.amount({id:'qa_charge',amount:10,ruleId:'order_not_submitted'})),0);
await a.page.evaluate(()=>window.rbAuditAdjustments.reload());await a.page.locator('[data-status]').selectOption('removed');await a.page.getByRole('button',{name:/JAM.*ทดสอบยอดหัก/}).click();assert.equal(await a.page.locator('.adc-adjust-total strong').innerText(),'฿0');await a.page.screenshot({path:path.resolve(root,'../audit-adjustments464-preview.png'),fullPage:false});
const staff=await device('graphic','JAM');{assert.equal(await staff.page.getByRole('button',{name:'＋ เพิ่มยอดหัก',exact:true}).count(),0)}
assert.deepEqual(errors,[]);console.log('PASS real audit page: add/reason/online totals; offline retention; two-device concurrent review; lost acknowledgement idempotency; removal and history persist across reload; no source resurrection');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
