const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {installSecureAuthMock}=require('./secure-auth-mock');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.RB_TEST_BROWSER_CHANNEL||'chrome'});try{
 const root=path.resolve(__dirname,'../..'),origin='http://127.0.0.1:8014';let order={id:'QA_RECOVERY',assignee:'JAM',name:'Recovery QA',product:'So Pink',type:'คัดคลิป',status:'inprogress',brief:'Current brief',updatedAt:100,_syncRevision:1},receipt=null,writes=0;const errors=[];
 const op={token:'recovery-qa',path:'/orders/work',method:'PATCH',conflict:true,data:{brief:'Old brief',status:'review',submitLink:'https://example.test/one',submitLinks:['https://example.test/one','https://example.test/two'],auditVersions:[{version:1,workLink:'https://example.test/one'},{version:2,workLink:'https://example.test/two'}],firstSubmittedAt:50,firstSubmittedBy:'Jam'}};
 const backup={operation:op,online:JSON.parse(JSON.stringify(order)),owner:'Jam',backedUpAt:100};
 async function device(role,name){const ctx=await browser.newContext();await ctx.route('**/*',route=>{const u=new URL(route.request().url()),f=path.resolve(root,'.'+u.pathname);return u.origin===origin&&f.startsWith(root+path.sep)&&fs.existsSync(f)?route.fulfill({path:f}):route.abort();});await installSecureAuthMock(ctx,{role,name});
 await ctx.route(/firebaseio\.com\/workflow_snapshots\/order_conflict_(backups|resolutions)_v1[^?]*\.json/,route=>{const r=route.request(),u=new URL(r.url());if(u.pathname.includes('backups'))return route.fulfill({json:{'qa-secure-user':{qa:backup}}});if(r.method()==='GET')return route.fulfill({json:u.pathname.endsWith('/recovery-qa.json')?receipt:{'recovery-qa':receipt}});receipt=r.postDataJSON();return route.fulfill({json:receipt});});
 await ctx.route(/firebaseio\.com\/orders(?:\/[^?]+)?\.json/,route=>{const r=route.request(),u=new URL(r.url());if(r.method()==='GET')return route.fulfill({headers:{ETag:'"'+order._syncRevision+'"','access-control-expose-headers':'ETag'},json:u.pathname==='/orders.json'?{work:order}:order});if(r.headers()['if-match']!=='"'+order._syncRevision+'"')return route.fulfill({status:412,body:''});order=r.postDataJSON();writes++;return route.fulfill({json:order});});
 const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/index.html');await p.waitForFunction(role=>window._rbUser?.role===role&&window.lpORD?.().some(o=>o.id==='QA_RECOVERY'),role);return p;}
 const worker=await device('graphic','JAM'),sup=await device('sup','View');await worker.evaluate(op=>localStorage.setItem('rb_order_write_queue_v1',JSON.stringify([op])),op);
 await sup.getByRole('button',{name:'เปิดสถานะระบบออนไลน์',exact:true}).click();await sup.getByRole('button',{name:'เวอร์ชันและคิวซิงก์ของอุปกรณ์',exact:true}).click();await sup.getByRole('button',{name:'ข้อมูลส่งงานที่สำรองออนไลน์',exact:true}).click();await sup.getByRole('button',{name:'ตรวจและกู้ข้อมูลส่งงาน',exact:true}).click();await sup.getByRole('button',{name:'กู้ข้อมูลส่งงานและยืนยันออนไลน์',exact:true}).waitFor();
 const preview=await sup.locator('dialog[open]').last().innerText();assert(preview.includes('brief'));assert(preview.includes('https://example.test/two'));await sup.getByRole('button',{name:'กู้ข้อมูลส่งงานและยืนยันออนไลน์',exact:true}).click();await sup.getByText('กู้ข้อมูลส่งงานออนไลน์สำเร็จ • เก็บสำเนาต้นฉบับและข้อมูลเดิมไว้แล้ว',{exact:true}).waitFor().catch(async e=>{console.log('Recovery dialog',await sup.locator('dialog[open]').last().innerText());throw e;});assert.equal(order.brief,'Current brief');assert.equal(order.status,'review');assert.equal(receipt.state,'committed');assert.equal(writes,1);
 await worker.evaluate(()=>window.fbRefreshOrders());await worker.waitForFunction(()=>window.rbOrderSync.pendingCount()===0&&window.lpORD().find(o=>o.id==='QA_RECOVERY').status==='review',{},{timeout:15000});await worker.reload();await worker.waitForFunction(()=>window.lpORD?.().some(o=>o.id==='QA_RECOVERY')&&window.rbOrderSync.pendingCount()===0);assert.equal(await worker.evaluate(()=>window.lpORD().find(o=>o.id==='QA_RECOVERY').submitLinks.length),2);assert.deepEqual(errors,[]);console.log('PASS supervisor UI restores two submissions; independent employee consumes central receipt and retains current brief after reload');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});

