const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {installSecureAuthMock}=require('./secure-auth-mock');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.RB_TEST_BROWSER_CHANNEL||'chrome'});try{
const root=path.resolve(__dirname,'../..'),origin='http://127.0.0.1:8014',notices={},errors=[];let fail=false,writeCount=0;
const rows=Array.from({length:206},(_,i)=>({name:'ขุนแผน คืนพลังชาย โทร.02-124-3032 '+String(i+1).padStart(3,'0'),prod:'ขุนแผน',st:'ใช้งาน',own:'BALL',pageId:String(i+1),shareFacebook:'Account full name '+i,creatorFacebook:'Creator full name '+i}));
rows.push({name:'เพจ 162'}, {name:'เพจ ๑๖๓'}, {name:'เพจ 164',st:'ใช้งาน',own:'BALL'});
rows[205].creatorFacebook='';
async function device(role,name){const ctx=await browser.newContext({viewport:{width:1280,height:900}});await ctx.route('**/*',route=>{const u=new URL(route.request().url()),file=path.resolve(root,'.'+u.pathname);return u.origin===origin&&file.startsWith(root+path.sep)&&fs.existsSync(file)?route.fulfill({path:file}):route.abort()});await installSecureAuthMock(ctx,{role,name});await ctx.route(/firebaseio\.com\/fbpages_base_snapshot\.json/,route=>route.fulfill({json:{items:rows,updatedAt:Date.now()}}));await ctx.route(/firebaseio\.com\/workflow_snapshots\/fbpage_notifications_v1(?:\/[^?]+)?\.json/,route=>{const req=route.request(),key=new URL(req.url()).pathname.split('/').pop().replace('.json','');if(req.method()!=='GET'){writeCount++;if(fail)return route.fulfill({status:403,json:{error:'denied'}});notices[key]=req.postDataJSON();return route.fulfill({json:notices[key]});}return route.fulfill({json:notices});});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/index.html',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window._rbUser?.name);await p.locator('#sidebar button').filter({hasText:'Graphic'}).click();await p.locator('.gsnav-btn').filter({hasText:'Facebook Pages'}).click();await p.waitForFunction(()=>document.querySelectorAll('#fbl-body tr[data-name]').length===206);await p.waitForSelector('select.rb-fbp-notification');return {p,ctx};}
const a=await device('sup','View'),p=a.p;assert.equal(await p.locator('#fbl-pager select').inputValue(),'all');assert.equal(await p.locator('#fbl-body tr[data-name]').count(),206);
await p.waitForFunction(()=>getComputedStyle(document.querySelector('.rb-fbp-table-shell')).maxHeight==='none');assert.equal(await p.locator('.rb-fbp-cell-main').first().textContent(),rows[0].name);assert.match(await p.locator('#fbl-body tr[data-name]').first().textContent(),/Creator full name 0/);
assert.equal(await p.locator('#fbl-body tr[data-name]').filter({hasText:/^เพจ\s*[0-9๐-๙]+/}).count(),0);assert.equal(await p.locator('#fbl-root').innerText().then(s=>s.includes('เฟสที่สร้าง: ยังไม่ระบุ')),false);assert.equal(await p.evaluate(()=>window._lfbData.length),209,'raw online source remains intact');
const first=p.locator('#fbl-body tr[data-name]').first();
async function selectedColor(page,value,dark=false){
  const colors=dark?{'':'rgb(66, 31, 40)','1':'rgb(60, 47, 19)','2':'rgb(20, 58, 45)'}:{'':'rgb(255, 240, 241)','1':'rgb(255, 242, 204)','2':'rgb(226, 246, 233)'};
  await page.waitForFunction(({value,color})=>{var el=document.querySelector('select.rb-fbp-notification');return el&&el.value===value&&getComputedStyle(el).backgroundColor===color;},{value,color:colors[value]});
}
await selectedColor(p,'');
await first.locator('select.rb-fbp-notification').click();
await p.locator('#rb-dd-popover').waitFor({state:'visible'});
assert.deepEqual(await p.locator('#rb-dd-popover .rb-dd-icon').evaluateAll(els=>els.map(el=>getComputedStyle(el).backgroundColor)),['rgb(220, 53, 69)','rgb(217, 137, 0)','rgb(22, 132, 81)'],'visible menu keeps all three notification colors');
await p.screenshot({path:path.resolve(root,'../facebook-notification478-menu.png')});
await p.locator('#rb-dd-popover .rb-dd-option').filter({hasText:'แจ้งรอบแรก (แชร์เพจ)'}).click();await first.getByText('บันทึกออนไลน์แล้ว',{exact:true}).waitFor();const key=await first.getAttribute('data-fbp-key');assert.equal(notices[key].value,'1');await selectedColor(p,'1');
const b=await device('graphic','BALL');await b.p.waitForFunction(()=>document.querySelector('select.rb-fbp-notification')?.value==='1');await selectedColor(b.p,'1');await b.p.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));await selectedColor(b.p,'1',true);
await b.p.locator('select.rb-fbp-notification').first().selectOption('2');await b.p.getByText('บันทึกออนไลน์แล้ว',{exact:true}).waitFor();await p.evaluate(()=>window.rbFacebookPageNotifications.pull());await p.waitForFunction(()=>document.querySelector('select.rb-fbp-notification')?.value==='2');await selectedColor(p,'2');await selectedColor(b.p,'2',true);
fail=true;await first.locator('select.rb-fbp-notification').selectOption('');await first.locator('.rb-fbp-notice-retry').waitFor().catch(async e=>{console.log(await p.evaluate(()=>({user:window._rbUser,row:document.querySelector('#fbl-body tr[data-name]')?.innerText,service:window.rbFacebookPageNotifications.state(window._fblSummaryData[0]),queue:window.rbPersistence?.pendingCount()})));throw e});assert.equal(await p.evaluate(()=>window.rbReleaseUpdate.blocked()),true,'pending status protects release reload');assert.equal(notices[key].value,'2','failed write cannot be shown as committed');fail=false;await first.locator('.rb-fbp-notice-retry').click();await first.getByText('บันทึกออนไลน์แล้ว',{exact:true}).waitFor();assert.equal(notices[key].value,'');await selectedColor(p,'');await p.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));await selectedColor(p,'',true);await first.locator('select.rb-fbp-notification').click();await p.screenshot({path:path.resolve(root,'../facebook-notification478-dark.png')});await p.locator('#rb-dd-popover .rb-dd-option').first().press('Escape');await p.evaluate(()=>document.documentElement.setAttribute('data-theme','light'));
await p.locator('#fbl-pager select').selectOption('50');await p.waitForFunction(()=>document.querySelectorAll('#fbl-body tr[data-name]').length===50);await p.locator('#fbl-pager select').selectOption('all');await p.waitForFunction(()=>document.querySelectorAll('#fbl-body tr[data-name]').length===206);
await p.locator('#fbl-q').fill('206');await p.waitForFunction(()=>document.querySelectorAll('#fbl-body tr[data-name]').length===1);await p.locator('.rb-fbp-filter-reset').click();await p.waitForFunction(()=>document.querySelectorAll('#fbl-body tr[data-name]').length===206);
for(const width of [1280,900,760,390,320]){await p.setViewportSize({width,height:900});assert.equal(await p.locator('#fbl-root').evaluate(el=>el.scrollWidth<=el.clientWidth+2),true,'page fits at '+width);assert.equal(await p.locator('.rb-fbp-table-shell').evaluate(el=>el.scrollWidth<=el.clientWidth+2),true,'table fits at '+width);}
await p.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));await first.scrollIntoViewIfNeeded();await p.screenshot({path:path.resolve(root,'../facebook-pages475-mobile.png')});await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>document.documentElement.setAttribute('data-theme','light'));await p.locator('.rb-fbp-titlebar').scrollIntoViewIfNeeded();await p.screenshot({path:path.resolve(root,'../facebook-pages475-desktop.png')});
await b.p.reload({waitUntil:'domcontentloaded'});await b.p.locator('#sidebar button').filter({hasText:'Graphic'}).click();await b.p.locator('.gsnav-btn').filter({hasText:'Facebook Pages'}).click();await b.p.waitForSelector('select.rb-fbp-notification');await b.p.waitForFunction(()=>document.querySelector('select.rb-fbp-notification')?.value==='');await selectedColor(b.p,'');
assert.deepEqual(errors,[]);assert.ok(writeCount>=4);console.log('PASS 206 pages, names/metadata, pagination/search, two-browser status sync, failure/retry, reset/reload, responsive widths and dark/light');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
