const {chromium}=require('playwright');
const assert=require('assert');
const {installSecureAuthMock}=require('./secure-auth-mock');

(async()=>{
  const target=process.argv[2]||'http://127.0.0.1:8015/';
  const now=Date.now();
  const order={id:'GR903',_fbKey:'qa_revision_image',name:'Image-only revision',camp1:'Image-only revision',product:'WOLF+',type:'กราฟิก',deadline:'2026-09-10',status:'revision',assignee:'DOM',submitLinks:['https://drive.google.com/original'],createdAt:now,updatedAt:now,auditVersions:[{jobId:'GR903',version:1,versionKey:'GR903:VER1',name:'Image-only revision',workLink:'https://drive.google.com/original',result:'issue',issueType:'รูปหรือข้อความไม่ถูกต้อง',note:'แก้ตามรูปตัวอย่าง',auditImages:[],fixImages:[],employeeSubmittedAt:0,correctionRequestedAt:now,updatedAt:now}]};
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const context=await browser.newContext({serviceWorkers:'block'});
  await installSecureAuthMock(context,{role:'graphic',name:'Dom',orders:[order]});
  await context.addInitScript(order=>{localStorage.setItem('rb_orders_v1',JSON.stringify([order]));},order);
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(target,{waitUntil:'commit',timeout:60000});
  await page.waitForSelector('#sidebar',{timeout:90000});
  await page.waitForFunction(()=>typeof window.openOM==='function'&&typeof window._rbInitOP==='function'&&typeof window.rbOpenEvidenceLightbox==='function',null,{timeout:90000});
  await page.evaluate(order=>{window._rbUser={role:'graphic',name:'Dom'};localStorage.setItem('rb_session',JSON.stringify({name:'Dom',role:'graphic',expiresAt:Date.now()+3600000}));localStorage.setItem('rb_orders_v1',JSON.stringify([order]));document.getElementById('rb-login-modal')?.remove();window._rbInitOP();},order);
  await page.locator('#sidebar button').filter({hasText:'Graphic'}).click();
  await page.locator('.gsnav-btn').filter({hasText:'สั่งงาน'}).click();
  await page.waitForSelector('[data-sub="order"].gsp-active');
  await page.getByRole('button',{name:'แก้ไขงาน'}).first().click();
  await page.getByRole('tab',{name:'ส่งงานภาพ',exact:true}).click();
  const upload=page.locator('#rb-team-version-workflow .rb-av-upload.is-fix input[type="file"]').first();
  await upload.setInputFiles({name:'corrected.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="60"><rect width="80" height="60" fill="#2a9d78"/></svg>')});
  await page.waitForFunction(()=>{const section=document.getElementById('rb-team-version-workflow'),state=section&&section._rbState&&section._rbState[0];return !!(state&&state.fixImages&&state.fixImages.length);},null,{timeout:30000});
  const uploadState=await page.evaluate(()=>{const section=document.getElementById('rb-team-version-workflow');return{sections:document.querySelectorAll('#rb-team-version-workflow').length,cards:section&&section.querySelectorAll('.rb-av-card').length,images:section&&section.querySelectorAll('.rb-av-fix-gallery img').length,state:section&&section._rbState&&section._rbState.map(item=>({version:item.version,result:item.result,fixImages:item.fixImages&&item.fixImages.length}))};});
  assert.strictEqual(uploadState.images,1,'the uploaded correction must render in its version gallery: '+JSON.stringify(uploadState));
  const primary=page.locator('#om-primary-btn');
  assert.match(await primary.innerText(),/ส่งตรวจอีกครั้ง/);
  await primary.click();
  await page.waitForTimeout(1200);
  const submitState=await page.evaluate(()=>{const rows=JSON.parse(localStorage.getItem('rb_orders_v1')||'[]'),message=document.querySelector('#rb-team-version-workflow .rb-av-save-message');return{status:rows[0]&&rows[0].status,message:message&&message.textContent,button:document.getElementById('om-primary-btn')&&document.getElementById('om-primary-btn').textContent};});
  assert.strictEqual(submitState.status,'review','image-only correction must move to review: '+JSON.stringify(submitState));
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('rb_orders_v1'))[0]);
  assert.strictEqual(saved.auditVersions[0].fixImages.length,1,'the corrected image must persist with its version');
  assert.strictEqual(saved.revisionSubmissions.at(-1).source,'version-audit-correction','the image-only correction must use the version-aware submission path');
  assert.deepStrictEqual(errors,[],'no JavaScript errors are allowed');
  await context.close();await browser.close();console.log('order revision image-only: all tests passed');
})().catch(error=>{console.error(error);process.exit(1);});
