const { chromium }=require('playwright');
const assert=require('assert');
(async()=>{
  const targetUrl=process.argv[2]||'http://127.0.0.1:8014/index.html?v=fix243';
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const page=await browser.newPage();
  page.setDefaultTimeout(15000);
  const browserErrors=[];
  page.on('pageerror',error=>browserErrors.push('pageerror: '+error.message));
  page.on('console',message=>{if(message.type()==='error'&&!/Failed to load resource/.test(message.text()))browserErrors.push('console: '+message.text());});
  await page.route('https://richbiotech-graphic-ads-default-rtdb.firebaseio.com/**',route=>route.abort());
  await page.route('https://**',route=>route.abort('blockedbyclient'));
  await page.addInitScript(()=>{
    const session={name:'วิว',role:'sup',expiresAt:Date.now()+3600000};
    localStorage.setItem('rb_session',JSON.stringify(session));
    localStorage.setItem('rb_users',JSON.stringify([{name:'วิว',role:'sup',pin:'1111',pinChanged:true}]));
    localStorage.setItem('rb_orders_v1',JSON.stringify([{id:'GR950',name:'Supervisor revision test',product:'WOLF+',type:'กราฟิก',deadline:'2026-08-23',status:'revision',assignee:'TER',createdAt:Date.now(),updatedAt:Date.now()}]));
    localStorage.setItem('lv_dash_v5',JSON.stringify({d:{'2026-8-22':[{empId:'ter',type:'hol'}]}}));
    localStorage.setItem('rb_theme','dark');
  });
  await page.goto(targetUrl,{waitUntil:'commit',timeout:60000});
  await page.waitForFunction(()=>typeof window.showTab==='function'&&typeof window.openOM==='function'&&typeof window.rbRefreshOrderLeaveGuard==='function',null,{timeout:90000});
  await page.evaluate(()=>{
    const team=[...document.querySelectorAll('nav button')].find(b=>(b.getAttribute('onclick')||'').includes("'team'"));
    window.showTab('team',team);
  });
  await page.locator('.gsnav-btn').filter({hasText:'สั่งงาน'}).click();
  await page.waitForSelector('#ord-add-btn');
  await page.locator('.ord-tab-btn').filter({hasText:'ทีมงาน'}).click();
  console.log('checking Supervisor existing-order action matrix');
  await page.evaluate(()=>{window._ordViewMode='order';window.openOM('GR950');});
  await page.waitForSelector('#rb-order-modal',{state:'visible'});
  assert.strictEqual(await page.locator('#om-resend-btn').count(),0,'legacy duplicate resubmit button must not exist for Supervisor');
  assert.match(await page.locator('#om-primary-btn').innerText(),/บันทึกงาน/,'Supervisor edit view must use one save action');
  assert.strictEqual(await page.locator('.rb-om-footer button:visible').count(),1,'Supervisor info tab must show exactly one action');
  await page.getByRole('tab',{name:'ส่งงาน/สรุปงาน',exact:true}).click();
  assert.match(await page.locator('#om-primary-btn').innerText(),/บันทึกส่งงานภาพ/,'Supervisor image tab must use its own save action');
  assert.strictEqual(await page.locator('.rb-om-footer button:visible').count(),1,'Supervisor image tab must show exactly one action');
  await page.getByRole('tab',{name:'ตรวจออดิต'}).click();
  assert.strictEqual(await page.locator('#om-primary-btn').isVisible(),false,'primary action must be hidden on Supervisor audit tab');
  assert.strictEqual(await page.locator('#om-audit-btns button:visible').count(),2,'Supervisor audit tab must show exactly two decisions');
  await page.getByRole('button',{name:'ปิด',exact:true}).click();
  console.log('checking Supervisor new-order submission');
  await page.locator('#ord-add-btn').click();
  await page.waitForSelector('#om-primary-btn');
  assert.strictEqual(await page.locator('#om-name').isDisabled(),false,'new order name must be editable');
  assert.match(await page.locator('#om-primary-btn').innerText(),/สั่งงาน/,'new order must show order action');
  await page.locator('#om-name').fill('Supervisor E2E test');
  await page.locator('#om-type').selectOption({index:1});
  await page.locator('#om-dl').fill('2026-08-23');
  assert.strictEqual(await page.locator('#om-st').inputValue(),'pending','new order must default to assigned status');
  await page.locator('#om-mb').selectOption('TER');
  await page.evaluate(()=>window.rbRefreshOrderLeaveGuard&&window.rbRefreshOrderLeaveGuard());
  const guard=await page.locator('#om-leave-guard').innerText();
  if(!/ใช้งานได้/.test(guard))console.error('leave guard diagnostics:',await page.evaluate(()=>({refresh:typeof window.rbRefreshOrderLeaveGuard,assignee:(document.getElementById('om-mb')||{}).value,deadline:(document.getElementById('om-dl')||{}).value,scripts:[...document.scripts].map(s=>s.src).filter(Boolean).filter(s=>s.includes('order-leave'))})),browserErrors);
  assert.match(guard,/ใช้งานได้/,'August 23 must be allowed when Ter is off on August 22');
  const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('rb_orders_v1')||'[]').length);
  await page.locator('#om-primary-btn').click();
  await page.getByRole('button',{name:'ยืนยันสั่งงาน'}).waitFor({state:'visible'});
  await page.getByRole('button',{name:'ยืนยันสั่งงาน'}).click();
  await page.waitForTimeout(500);
  const after=await page.evaluate(()=>JSON.parse(localStorage.getItem('rb_orders_v1')||'[]').length);
  if(after!==before+1){
    console.error('browser errors:',browserErrors);
    console.error('validation:',await page.locator('#om-validation-msg').allTextContents());
    console.error('button:',await page.locator('#om-primary-btn').innerText());
  }
  assert.strictEqual(after,before+1,'new order must be persisted locally');
  assert.strictEqual(await page.locator('#om-primary-btn').isVisible(),false,'successful order must close the modal');
  console.log('order-supervisor e2e: all tests passed');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
