const {chromium}=require('playwright');
const assert=require('assert');

(async()=>{
  const target=process.argv[2]||'http://127.0.0.1:8014/index.html?v=fix280-order-image-submit-links';
  const order={id:'GR999',name:'Image delivery link test',product:'WOLF+',type:'กราฟิก',deadline:'2026-08-26',status:'inprogress',assignee:'DOM',submitLinks:['https://example.com/work-1'],imageSubmitLinks:['https://example.com/image-1'],createdAt:Date.now(),updatedAt:Date.now()};
  const browser=await chromium.launch({headless:true,channel:'chrome'});
  const context=await browser.newContext({viewport:{width:390,height:844}});
  await context.addInitScript(order=>{
    localStorage.setItem('rb_session',JSON.stringify({name:'Dom',role:'graphic',expiresAt:Date.now()+3600000}));
    localStorage.setItem('rb_orders_v1',JSON.stringify([order]));
  },order);
  await context.route(/firebaseio\.com/,route=>route.abort('blockedbyclient'));
  await context.route('https://**',route=>route.abort('blockedbyclient'));
  const page=await context.newPage(),errors=[];
  page.setDefaultTimeout(15000);
  page.on('pageerror',error=>errors.push(error.message));
  console.log('stage: load page');
  await page.goto(target,{waitUntil:'commit',timeout:60000});
  await page.waitForSelector('#sidebar',{state:'attached',timeout:90000});
  await page.waitForFunction(()=>typeof window.openOM==='function'&&typeof window._rbInitOP==='function',null,{timeout:90000});
  console.log('stage: open order');
  await page.evaluate(()=>{
    const team=[...document.querySelectorAll('nav button')].find(button=>(button.getAttribute('onclick')||'').includes("'team'"));
    window.showTab('team',team);
  });
  await page.locator('.gsnav-btn').filter({hasText:'สั่งงาน'}).click();
  await page.waitForSelector('[data-sub="order"].gsp-active');
  await page.evaluate(()=>window.openOM('GR999'));
  await page.waitForSelector('#rb-order-modal',{state:'visible'});
  console.log('stage: audit sync');
  await page.getByRole('tab',{name:'ตรวจออดิต'}).click();
  assert.strictEqual(await page.locator('#om-uplink').inputValue(),'https://example.com/work-1','work links must synchronize to Audit Link Ver fields');
  await page.getByRole('tab',{name:'ประเภทงาน'}).click();
  console.log('stage: image link editor');
  await page.getByRole('tab',{name:'ลิงก์ส่งงานภาพ'}).click();
  assert.strictEqual(await page.locator('#om-image-submitlinks-rows input').count(),1,'saved image link must reopen');
  assert.strictEqual(await page.locator('#om-image-submitlinks-rows input').first().inputValue(),'https://example.com/image-1');
  await page.locator('#om-add-image-submitlink').click();
  await page.locator('#om-image-submitlinks-rows input').nth(1).fill('https://example.com/image-2');
  console.log('stage: image delivery sync');
  await page.getByRole('tab',{name:'ส่งงานภาพ',exact:true}).click();
  assert.strictEqual(await page.locator('#om-image-submitlink-list a').count(),2,'image links must synchronize to the image-work page');
  assert.strictEqual(await page.locator('#om-image-submitlink-list a').nth(1).getAttribute('href'),'https://example.com/image-2');
  await page.getByRole('tab',{name:'ประเภทงาน'}).click();
  console.log('stage: separation check');
  await page.getByRole('tab',{name:'ลิงก์ส่งงาน',exact:true}).click();
  assert.strictEqual(await page.locator('#om-submitlinks-rows input').first().inputValue(),'https://example.com/work-1','switching tabs must not overwrite work links');
  await page.getByRole('tab',{name:'ลิงก์ส่งงานภาพ'}).click();
  assert.strictEqual(await page.locator('#om-image-submitlinks-rows input').nth(1).inputValue(),'https://example.com/image-2','switching tabs must retain image links');
  console.log('stage: save order');
  await page.locator('#om-primary-btn').click();
  await page.waitForTimeout(300);
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('rb_orders_v1'))[0]);
  assert.deepStrictEqual(saved.submitLinks,['https://example.com/work-1'],'work links must stay separate');
  assert.deepStrictEqual(saved.imageSubmitLinks,['https://example.com/image-1','https://example.com/image-2'],'all image links must save');
  assert.deepStrictEqual(errors,[],'no JavaScript errors are allowed');
  await browser.close();
  console.log('order image submit links: passed');
})().catch(error=>{console.error(error);process.exit(1);});
