const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {installSecureAuthMock}=require('./secure-auth-mock');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.RB_TEST_BROWSER_CHANNEL||'chrome'});try{
 const root=path.resolve(__dirname,'../..'),db={},errors=[];let etag=1,sequence=1000,offline=false;
 async function context(role,name){const c=await browser.newContext({viewport:{width:1280,height:1000}});await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin!=='http://127.0.0.1:8014')return r.abort();const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)?r.fulfill({path:file}):r.fulfill({status:404,body:''});});await installSecureAuthMock(c,{role,name});await c.route(/firebaseio\.com\/orders(?:\/[^?]+)?\.json/,async r=>{if(offline)return r.abort('internetdisconnected');const req=r.request(),key=new URL(req.url()).pathname.split('/')[2]?.replace('.json','');if(req.method()==='OPTIONS')return r.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,PUT,OPTIONS','access-control-allow-headers':'*'}});if(req.method()==='GET')return r.fulfill({headers:{ETag:'"'+etag+'"','access-control-allow-origin':'*','access-control-expose-headers':'ETag'},json:key?(db[key]||null):db});assert.equal(req.method(),'PUT');assert.equal(req.headers()['if-match'],'"'+etag+'"');db[key]=req.postDataJSON();etag++;return r.fulfill({headers:{'access-control-allow-origin':'*'},json:db[key]});});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8014/index.html');await p.waitForFunction(()=>window._rbUser?.uid&&window.rbPersonalWork&&window.openOM);await p.evaluate(()=>{window.rbReserveOrderId=async()=> 'GR'+(++window.__qaSequence);window.__qaSequence=1000;});if(Object.keys(db).length)await p.waitForFunction(expected=>window.lpORD?.().some(o=>o.id===expected.id&&o.updatedAt===expected.updatedAt),Object.values(db)[0]);return p;}
 const worker=await context('graphic','DOM');await worker.evaluate(()=>window.openOM(null,true));await worker.locator('#rb-personal-work').waitFor();
 const row=worker.locator('.rb-pt-row').first();for(const [i,value] of ['DOM A','Page A','Campaign A','https://example.test/ad-a'].entries())await row.locator('input').nth(i).fill(value);
 await worker.locator('#rb-personal-work>button').click();const row2=worker.locator('.rb-pt-row').nth(1);for(const [i,value] of ['DOM B','Page B','Campaign B','https://example.test/ad-b'].entries())await row2.locator('input').nth(i).fill(value);
 await worker.locator('#rb-personal-work>label input[type=url]').fill('https://example.test/shared');await worker.locator('#rb-personal-work input[type=date]').fill('2026-10-22');
 if(process.env.RB_PERSONAL_SCREENSHOT)await worker.screenshot({path:process.env.RB_PERSONAL_SCREENSHOT,fullPage:false});await worker.locator('.rb-om-tab').filter({hasText:'ตรวจออดิต'}).click();await worker.waitForFunction(()=>document.querySelectorAll('#rb-audit-version-workflow .rb-av-card').length===2);assert.match(await worker.locator('#rb-audit-version-workflow').innerText(),/Campaign B/);assert.match(await worker.locator('#rb-audit-version-workflow').innerText(),/Page B/);assert.match(await worker.locator('#rb-audit-version-workflow').innerText(),/shared/);
 await worker.locator('.rb-om-tab').filter({hasText:'ประเภทงาน'}).click();await worker.locator('#om-save-btn').click();await worker.waitForFunction(()=>document.querySelector('#rb-order-modal').style.display==='none').catch(async e=>{console.log('feedback',await worker.locator('#om-submit-feedback').innerText());throw e;});
 const key=Object.keys(db)[0];assert.ok(key);assert.equal(db[key].status,'inprogress');assert.equal(db[key].assignee,'DOM');assert.equal(db[key].personalCampaigns[1].fbName,'DOM B');assert.equal(db[key].type,'เทสส่วนตัว');assert.equal(db[key].imageSubmitLinks.length,1);
 await worker.evaluate(key=>{window._ordViewMode='team';window.openOM(key);},key);await worker.context().setOffline(true);await worker.locator('#om-primary-btn').click();await worker.waitForFunction(()=>window.rbOrderSync.pendingCount()>0);assert.equal(db[key].status,'inprogress','offline submit must not claim server acceptance');await worker.context().setOffline(false);await worker.evaluate(()=>{window.dispatchEvent(new Event('online'));window.rbOrderSync.flush();});await worker.waitForFunction(()=>window.rbOrderSync.pendingCount()===0);assert.equal(db[key].status,'review');assert.ok(db[key].firstSubmittedAt);assert.equal(db[key].reviewRounds.events.filter(e=>e.kind==='submitted').length,1);
 const audit=await context('audit','QA Audit');await audit.evaluate(key=>{window._ordViewMode='audit';window.openOM(key);},key);await audit.locator('.rb-om-tab').filter({hasText:'ตรวจออดิต'}).click();await audit.waitForFunction(()=>document.querySelectorAll('#rb-audit-version-workflow .rb-av-card').length===2);assert.match(await audit.locator('#rb-audit-version-workflow').innerText(),/Campaign A/);
 await audit.evaluate(()=>{document.querySelectorAll('#rb-audit-version-workflow .rb-av-result-input').forEach(e=>{e.value='issue';e.dispatchEvent(new Event('change',{bubbles:true}));});});await audit.locator('#rb-audit-version-workflow .rb-av-note-input').first().fill('แก้แคมเปญ A');await audit.locator('#om-audit-btns button').last().click();await audit.waitForFunction(()=>document.querySelector('#rb-order-modal').style.display==='none'||document.querySelector('#om-submit-feedback')?.textContent.includes('บันทึกออนไลน์แล้ว')).catch(async e=>{console.log('audit diagnostic',await audit.locator('#om-submit-feedback').innerText(),db[key].status);throw e;});assert.equal(db[key].status,'revision');
 await worker.reload();await worker.waitForFunction(()=>window._rbUser?.uid&&window.lpORD?.().some(o=>o.status==='revision'));await worker.evaluate(key=>{window._ordViewMode='team';window.openOM(key);},key);await worker.locator('.rb-om-tab').filter({hasText:'ส่งงาน/สรุปงาน'}).click();assert.match(await worker.locator('#rb-team-version-workflow').innerText(),/แก้แคมเปญ A/);assert.equal(await worker.locator('#rb-personal-work .rb-pt-row input:enabled').count(),0);

 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aAZkAAAAASUVORK5CYII=','base64');
 const uploads=worker.locator('#rb-team-version-workflow .rb-av-upload.is-fix input');const count=await uploads.count();assert.ok(count>0);
 for(let i=0;i<count;i++){await uploads.nth(i).setInputFiles({name:'fix.png',mimeType:'image/png',buffer:png});await worker.waitForFunction(()=>document.querySelector('#rb-team-version-workflow')?._rbState?.filter(s=>s.result==='issue').every(s=>s.fixImages?.length)||document.querySelector('#rb-team-version-workflow')?._rbState?.some(s=>s.fixImages?.length));}
 await worker.locator('#rb-team-version-workflow .rb-av-employee-save').click();await worker.waitForFunction(()=>document.querySelector('#rb-team-version-workflow .rb-av-save-message')?.textContent.includes('ส่งกลับให้ Audit แล้ว'));assert.equal(db[key].status,'review');assert.equal(db[key].revisionSubmissions.length,1);assert.equal(db[key].personalCampaigns[1].name,'Campaign B');
 await audit.reload();await audit.waitForFunction(()=>window.lpORD?.().some(o=>o.status==='review'&&o.revisionSubmissions?.length===1));await audit.evaluate(key=>{window._ordViewMode='audit';window.openOM(key);},key);await audit.locator('.rb-om-tab').filter({hasText:'ตรวจออดิต'}).click();await audit.locator('#om-audit-btns button').first().click();await audit.waitForFunction(()=>document.querySelector('#om-submit-feedback')?.textContent.includes('ออนไลน์เรียบร้อยแล้ว')||document.querySelector('#rb-order-modal').style.display==='none');assert.equal(db[key].status,'done');
 const other=await context('graphic','BALL');await other.waitForFunction(()=>window.lpORD?.().some(o=>o.personalTest));await other.evaluate(key=>window.openOM(key),key);assert.equal(await other.locator('#rb-personal-work input:enabled').count(),0);assert.equal(await other.evaluate(()=>window.rbPersonalWork.prepare()),false);
 await worker.setViewportSize({width:390,height:844});await worker.locator('.rb-om-tab').filter({hasText:'ประเภทงาน'}).click();assert.equal(await worker.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);
 assert.deepEqual(errors,[]);console.log('Personal tests: create, two VERs, shared link, save draft, submit, independent Audit, correction, ownership, mobile passed.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
