const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {installSecureAuthMock}=require('./secure-auth-mock');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.RB_TEST_BROWSER_CHANNEL||'chrome'});try{
 const root=path.resolve(__dirname,'../..'),db={},errors=[];let etag=1,sequence=1000,offline=false;
 async function context(role,name){const c=await browser.newContext({viewport:{width:1280,height:1000}});await c.route('**/*',async r=>{const u=new URL(r.request().url());if(u.origin!=='http://127.0.0.1:8014')return r.abort();const file=path.resolve(root,'.'+u.pathname);return file.startsWith(root+path.sep)&&fs.existsSync(file)?r.fulfill({path:file}):r.fulfill({status:404,body:''});});await installSecureAuthMock(c,{role,name});await c.route(/firebaseio\.com\/orders(?:\/[^?]+)?\.json/,async r=>{if(offline)return r.abort('internetdisconnected');const req=r.request(),key=new URL(req.url()).pathname.split('/')[2]?.replace('.json','');if(req.method()==='OPTIONS')return r.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,PUT,OPTIONS','access-control-allow-headers':'*'}});if(req.method()==='GET')return r.fulfill({headers:{ETag:'"'+etag+'"','access-control-allow-origin':'*','access-control-expose-headers':'ETag'},json:key?(db[key]||null):db});assert.equal(req.method(),'PUT');assert.equal(req.headers()['if-match'],'"'+etag+'"');db[key]=req.postDataJSON();etag++;return r.fulfill({headers:{'access-control-allow-origin':'*'},json:db[key]});});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8014/index.html');await p.waitForFunction(()=>window._rbUser?.uid&&window.rbPersonalWork&&window.openOM);await p.evaluate(()=>{window.rbReserveOrderId=async()=> 'GR'+(++window.__qaSequence);window.__qaSequence=1000;});if(Object.keys(db).length)await p.waitForFunction(expected=>window.lpORD?.().some(o=>o.id===expected.id&&o.updatedAt===expected.updatedAt),Object.values(db)[0]);return p;}

 const worker=await context('spec','TER');await worker.evaluate(()=>window.openOM(null));
 await worker.locator('#om-type').selectOption('ยิงแอด');await worker.locator('#om-name').fill('Specialist assignment QA');await worker.locator('#om-mb').selectOption('DOM');await worker.locator('#om-dl').fill('2026-10-22');
 await worker.evaluate(()=>window.saveOrder(true));await worker.waitForFunction(()=>document.querySelector('#rb-order-modal').style.display==='none').catch(async e=>{console.log(await worker.locator('#om-submit-feedback').innerText());throw e;});
 const saved=Object.values(db)[0];assert.ok(saved);assert.equal(saved.assignee,'DOM');assert.equal(saved.name,'Specialist assignment QA');assert.ok(!saved.personalTest);
 await worker.reload();await worker.waitForFunction(()=>window.lpORD?.().some(o=>o.name==='Specialist assignment QA'));
 assert.deepEqual(errors,[]);console.log('PASS Specialist regular order save and reload with assigned employee');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
