const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const window={addEventListener(){},_rbUser:{name:'BALL',role:'graphic'},lpORD:()=>[]};
const document={querySelector:()=>null,documentElement:{}};
vm.runInNewContext(fs.readFileSync('snippets/audit-deduction-center-v1.js','utf8'),{window,document,localStorage:{getItem:()=>null},MutationObserver:class{observe(){}},setTimeout(){},console});
const api=window._rbAuditDeductionTest;
const pairs=[['MOS','sheet_10g7jza','sheet_6l2icn'],['TER','sheet_1e5nhz0','sheet_k8n3y5'],['JAM','sheet_1ha4v05','sheet_y71aic'],['DOM','sheet_1qsxwht','sheet_ribsm0'],['NUNE','sheet_h7dbwp','sheet_1cjtdhc'],['BALL','sheet_s32d7e','sheet_1q2b78z']];
const rows=pairs.flatMap(([employee,oldId,newId])=>[oldId,newId].map((id,i)=>({id,employee,ruleId:'sheet_import',period:'2026-09',title:'ไม่เคลียร์ตารางสรุปแอด',detectedAt:new Date(2026,8,4).getTime(),dueAt:new Date(2026,8,i?4:1).getTime(),amount:50,sourceStatus:'หักเงินแล้ว'})));
const active=api.activeDeductionRows(rows);
assert.equal(active.length,6);
assert.equal(api.sumRows(active).total,300,'six confirmed duplicate pairs must count only once');
for(const [employee] of pairs)assert.equal(api.personTotals(active.filter(x=>x.employee===employee)).total,50);
assert.equal(api.activeDeductionRows([rows[0]]).length,1,'do not drop history if its replacement has not arrived');
assert.equal(api.activeDeductionRows([rows[0],{...rows[1],amount:100}]).length,2,'do not merge amounts that differ');
assert.equal(api.activeDeductionRows([rows[0],{...rows[1],employee:'OTHER'}]).length,2,'do not merge different people');
assert.equal(api.activeDeductionRows([rows[0],{...rows[1],detectedAt:new Date(2026,8,5).getTime()}]).length,2,'repeated offenses on another date remain separate');
assert.equal(api.activeDeductionRows([rows[0],{...rows[1],id:'another-genuine-row'}]).length,2,'only explicitly identified duplicate records are retired');
const pending={id:'pending',ruleId:'sheet_import',employee:'BALL',dueAt:1,amount:70};
const t=api.personTotals([active[5],pending]);
assert.equal(t.total,50);assert.equal(t.pending,70);assert.equal(t.count,2);
console.log('audit per-person totals and duplicate retirement passed');
