const assert=require('assert');
const fs=require('fs');
const path=require('path');

const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'snippets','commission-center-v1.js'),'utf8');
const css=fs.readFileSync(path.join(root,'snippets','commission-center-v1.css'),'utf8');
const parseDateSource=js.match(/function parseDate\(v\)\{[^\r\n]+/);
assert.ok(parseDateSource,'date parser must be present');
const parseDate=Function(parseDateSource[0]+';return parseDate')();
assert.strictEqual(parseDate('05/07/69'),'2026-07-05','short Buddhist year 69 must map to 2026');
assert.strictEqual(parseDate('05/07/2569'),'2026-07-05','full Buddhist year 2569 must map to 2026');
const rankingSource=js.match(/function staffRanking\(ranked\)\{[^\r\n]+/);
assert.ok(rankingSource,'staff ranking renderer must be present');
const staffRanking=Function('money','esc',rankingSource[0]+';return staffRanking')(value=>'฿'+value,value=>String(value));
const rankingHtml=staffRanking([
  {employee:'FIRST',sum:{commission:500,products:3,days:20}},
  {employee:'SECOND',sum:{commission:300,products:2,days:18}},
  {employee:'THIRD',sum:{commission:100,products:1,days:12}},
  {employee:'FOURTH',sum:{commission:50,products:1,days:8}}
]);
assert.ok(rankingHtml.includes('FIRST')&&rankingHtml.includes('SECOND')&&rankingHtml.includes('THIRD'),'ranking must render the three highest earners');
assert.ok(!rankingHtml.includes('FOURTH'),'ranking must exclude employees below third place');

assert.ok(html.includes('commission-center-v1.css?v=fix362'),'commission stylesheet must be loaded');
assert.ok(html.includes('commission-center-v1.js?v=fix362'),'commission runtime must be loaded');
assert.ok(js.includes('data-cc-staff-product'),'monthly detail must provide product tabs');
assert.ok(js.includes("num(r.ads)>0||num(r.commission)>0"),'monthly detail must hide zero-value dates');
assert.ok(js.includes('data-cc-action="save-all-goals"'),'supervisor must be able to save every employee goal');
assert.ok(js.includes("CLOUD_STORE+'/goals/'"),'goals must use targeted cloud persistence');
assert.ok(js.includes('ภาพรวมค่าคอมทุกคน'),'supervisor overview must include every employee');
assert.ok(css.includes('.cc-month-table'),'monthly product table styles must be loaded');
assert.ok(css.includes('.cc-goal-grid'),'goal editor styles must be loaded');
assert.ok(js.includes('loadAll(false)'),'commission data must paint from cache without starting hidden-page network work');
assert.ok(js.includes('loadAll(true)'),'commission data must hydrate when its page is opened');
assert.ok(js.includes('function saveSourceLocal(rows)'),'large commission cache must be stored through a quota-safe helper');
assert.ok(js.includes('json.length>750000'),'large source snapshots must not crowd out operational save queues');
assert.ok(js.includes('window._rbCommissionMount'),'commission app must expose a deterministic late-panel mount hook');
assert.ok(js.includes('MutationObserver'),'commission app must recover when the real panel is created after page load');
assert.ok(js.includes('mountIfNeeded()'),'commission app must mount itself when the panel appears');
assert.ok(js.includes("if(r==='audit')return'audit'"),'Audit must have its own entry view');
assert.ok(js.includes("r==='graphic'||r==='ads'||r==='spec'"),'Graphic, Ads and Specialist must have the employee card view');
assert.ok(js.includes('เลือกการ์ดเพื่อดูรายละเอียด'),'view-only Ads users without a commission card need an accurate prompt');
assert.ok(js.includes('function enforceAdsAccess()'),'Ads users must be able to open the commission tab');
assert.ok(js.includes("return'supervisor'"),'Supervisor must have team view');
assert.ok(js.includes('data-cc-view'),'Supervisor must be able to preview every user view');
assert.ok(js.includes('<option value="staff:team"'),'Supervisor must have one consolidated Graphic & Ads preview');
assert.ok(js.includes('Graphic & Ads · มุมมองพนักงาน'),'the consolidated employee view must be labelled by department');
assert.ok(js.includes("key==='staff:team'?'Graphic & Ads'"),'the preview notice must identify the department instead of an individual employee');
assert.ok(!js.includes('employees().map(function(emp){var value=\'staff:\'+emp'),'individual employee names must not be generated in the view selector');
assert.ok(js.includes("actual==='audit'||actual==='supervisor'"),'Supervisor must have full Audit entry permission');
assert.ok(js.includes('สิทธิ์ Supervisor แบบเต็ม'),'Supervisor Audit management permission must be explained');
assert.ok(js.includes('function productsForEmployee(employee)'),'Audit entry must filter products by responsible employee');
assert.ok(js.includes('data-cc-action="toggle-product-form"'),'Supervisor must be able to open the add-product form');
assert.ok(js.includes("CLOUD_STORE+'/catalog/'"),'new product assignments must persist to shared storage');
assert.ok(js.includes('data-cc-product-employee'),'new products must be assigned to responsible employees');
assert.ok(js.includes('ตัวอย่างนี้เป็นแบบอ่านอย่างเดียว'),'staff preview mode must explain its read-only permission');
assert.ok(js.includes("CLOUD_STORE='/commission_center_v1'"),'commission edits must persist to shared storage');
assert.ok(js.includes("CLOUD_STORE+'/records/'"),'commission rows must save independently so concurrent Audit work cannot overwrite other records');
assert.ok(js.includes("CLOUD_STORE+'/locks/'"),'period locks must save independently from commission rows');
assert.ok(js.includes('data-cc-action="save-audit"'),'Audit must be able to save ad-spend rows');
assert.ok(js.includes('data-cc-action="toggle-lock"'),'Supervisor must be able to lock a period');
assert.ok(js.includes('ค่าคอมของทีม'),'staff view must show the team card dashboard');
assert.ok(js.includes('data-cc-team-card'),'every employee must be represented by a commission card');
assert.ok(js.includes('data-cc-staff-person'),'staff must be able to inspect teammate details');
assert.ok(js.includes('พนักงานทุกคนดูค่าคอมของทีม'),'staff team visibility must be explained');
assert.ok(css.includes('.cc-team-grid'),'team cards must have a responsive layout');
assert.ok(js.includes('พนักงาน + วันที่ + สินค้า'),'duplicate protection must be visible');
assert.ok(js.includes('function commissionForAds(value)'),'new Audit entries must use the daily ad-spend tier rule');
assert.ok(js.includes('function auditViewEnhanced()'),'Audit must show a live commission summary while entering ad spend');
assert.ok(js.includes('function updateAuditPreview(app,activeInput)'),'live commission totals must update without saving');
assert.ok(js.includes('data-cc-live-commission'),'Audit must visibly expose the commission calculated for today');
assert.ok(js.includes('function staffRanking(ranked)'),'staff view must rank the top three commission earners from current period data');
assert.ok(js.includes('ถ้วยรางวัลค่าคอมประจำรอบ'),'staff view must label the three-place award podium');
assert.ok(js.includes('function staffDetailModal(employee,allRows)'),'staff detail must open in a focused popup');
assert.ok(js.includes('data-cc-action="toggle-staff-daily"'),'the popup must switch to daily ad-spend detail');
assert.ok(js.includes('data-cc-daily-date'),'daily commission detail must support selecting a date');
assert.ok(css.includes('.cc-modal-backdrop'),'staff detail popup must have modal styling');
assert.ok(css.includes('.cc-podium'),'top-three ranking must have a responsive podium layout');
assert.ok(js.includes("gid:'647383985'"),'July 2569 Google Sheet must be imported');
assert.ok(js.includes("gid:'1514012256'"),'August 2569 Google Sheet must be imported');
assert.ok(js.includes("employee:'BALL',range:'CZ7:DN37'"),'each team member must use the correct source block');
assert.ok(js.includes('function parseTeamBlock(csv,employee,label)'),'team commission blocks must be parsed independently');
assert.ok(js.includes("TEAM_FULL_RANGE='H7:DZ37'"),'each month must be fetched once instead of one request per employee');
assert.ok(js.includes('TEAM_SHEETS.map(function(sheet)'),'July and August imports must use only two sheet requests');
assert.ok(js.includes("function ensureTeamImport()"),'each browser must import the new July-August source once after deployment');
assert.ok(js.includes("if(!date||rawAds==='')return"),'blank formula rows must not become zero-value records');
assert.ok(js.includes('else if(y>=60&&y<100)y+=1957'),'short Thai Buddhist years must resolve to Gregorian dates');
assert.ok(js.includes('if(ads<=15000)return 0;if(ads<=20000)return 70'),'commission must start above 15,000 baht');
assert.ok(js.includes('Promise.all([reference,standard,fetchTeamSheets()])'),'existing and July-August sources must merge without replacing saved dashboard rows');
assert.ok(js.includes('function parseReference(html)'),'a public read-only source must back up the Google Sheet connection');
assert.ok(css.includes('@media(max-width:700px)'),'commission page must support mobile layouts');
console.log('commission center static contract: passed');
