const {JSDOM}=require('jsdom');
const fs=require('fs');const assert=require('node:assert/strict');
const dom=new JSDOM('<main></main>',{runScripts:'outside-only'}),w=dom.window;
w.eval(fs.readFileSync('snippets/employee-job-details-v1.js','utf8'));
const api=w.rbEmployeeJobDetails;
const order={id:'TEST1',name:'เดิม',product:'So Pink',assignee:'DOM',deadline:'2026-09-12',type:'คัดคลิป',hook:'เก่า',brief:'เดิม',rawLink:'preserve'};
assert.equal(api.allowed(order,{name:'DOM',role:'graphic'}),true);
for(const user of [{name:'MOS',role:'spec'},{name:'DOM',role:'audit'},null])assert.equal(api.allowed(order,user),false);
w._rbUser={name:'DOM',role:'graphic'};
let saved;
api.mount(w.document.querySelector('main'),order,{rows:()=>[{brand:'So Pink',name:'ใหม่',hook:'HOOK A',link:'https://example.com/clip',script:'https://example.com/script'},{brand:'So Pink',name:'ใหม่',hook:'HOOK B'},{brand:'JUDO',name:'สินค้าอื่น',hook:'ห้ามปน'}],presets:['บรีฟสำเร็จรูป'],save:async fields=>{saved=fields;}});
const select=w.document.querySelectorAll('select'),button=w.document.querySelector('button');
assert(!select[0].textContent.includes('สินค้าอื่น'));
assert.equal(select[0].value,'เดิม');assert.equal(select[1].value,'เก่า');
select[0].value='ใหม่';select[0].dispatchEvent(new w.Event('change'));
assert.equal(select[1].value,'');assert(select[1].textContent.includes('HOOK A'));assert(!select[1].textContent.includes('เก่า'));
select[1].value='HOOK A';select[2].value='HOOK B';select[3].value='บรีฟสำเร็จรูป';select[3].dispatchEvent(new w.Event('change'));
assert.equal(w.document.querySelector('textarea').value,'บรีฟสำเร็จรูป');
(async()=>{await button.onclick();assert.equal(saved.name,'ใหม่');assert.equal(saved.rawLink,'https://example.com/clip');assert.equal(saved.sheetLink,'https://example.com/script');assert.equal(saved.brief,'บรีฟสำเร็จรูป');assert.equal(saved.hook2,'HOOK B');assert.deepEqual(Object.keys(saved).sort(),['brief','hook','hook2','name','rawLink','sheetLink','title']);assert.equal(order.deadline,'2026-09-12');assert.equal(order.rawLink,'preserve');
w._rbUser={name:'MOS',role:'spec'};assert.equal(api.read(order),null);saved=null;await button.onclick();assert.equal(saved,null);
api.mount(w.document.querySelector('main'),order,{rows:()=>[],presets:[]});assert.equal(w.document.querySelector('#rb-employee-job-details'),null);
console.log('PASS: dependent dropdowns, legacy values, brief preset, own-job guard, field isolation');})();

const refs=[{brand:'So Pink',name:'ใหม่',hook:'A',link:'https://example.com/clip',script:'https://example.com/script'},{brand:'So Pink',name:'ใหม่',hook:'B',link:'https://example.com/other',script:'https://example.com/script'}];
assert.equal(api.references(refs,order,'ใหม่','A').rawLink,'https://example.com/clip');
assert.equal(api.references(refs,order,'ใหม่','').rawLink,'');
assert.equal(api.references(refs,order,'ใหม่','').sheetLink,'https://example.com/script');
assert.equal(api.references(refs,order,'เดิม','').rawLink,'preserve');
assert.equal(api.references(refs,order,'ชื่ออื่น','').rawLink,'');
