const assert=require('node:assert/strict'),fs=require('node:fs'),{JSDOM}=require('jsdom');
function setup(){const d=new JSDOM('<div id="fbl-root"></div><span id="lfb-ts"></span><button id="lfb-upd"></button>',{url:'https://example.test',runScripts:'outside-only'}),w=d.window;w._rbUser={role:'sup',name:'Tester'};w._fpMerge=r=>r;w._renderFbList=(root,r)=>{w.rows=r;};for(const f of ['facebook-pages-source-v1.js'])w.eval(fs.readFileSync('snippets/'+f,'utf8'));return d;}
(async()=>{
 const d=setup(),w=d.window;const source=require('./facebook-pages-fixture.cjs')(w.rbFacebookPagesSource),old=source.filter((r,i,all)=>all.findIndex(x=>x.shareFacebook===r.shareFacebook)===i);
 let sheetFetches=0;w.fetch=()=>{sheetFetches++;throw new Error('must not refresh sheet on open');};w.fbGet=(path,cb)=>cb(null,{items:source,updatedAt:Date.now(),schemaVersion:438});w.localStorage.setItem('rb_fbpages_cache_v1',JSON.stringify(old));w.localStorage.setItem('rb_fbpages_refreshed_v1','1');w.eval(fs.readFileSync('snippets/manual-refresh-v1.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));w._initFbList();await new Promise(r=>setTimeout(r,10));assert.equal(w.rows.length,200);assert.equal(sheetFetches,0,'shared online data loads without refreshing Google Sheets');w._initFbList();await new Promise(r=>setTimeout(r,10));assert.equal(w.rows.length,200);d.window.close();
 const e=setup(),x=e.window;let writes=[];x.fbGet=(path,cb)=>cb(null,null);x.fbSet=(path,data)=>{writes.push({path,data});return Promise.resolve(true);};x.fetch=()=>Promise.resolve({ok:true,text:()=>Promise.resolve('ชื่อเพจ,สินค้า,สถานะเพจ,เจ้าของเพจ,Facebook ที่สามารถแชร์ได้\nA,P,ใช้งาน,NUNE,Same\nB,P,ใช้งาน,NUNE,Same')});x.eval(fs.readFileSync('snippets/facebook-pages-inline-editor-v2.js','utf8'));await x._lfbFetch();assert.equal(writes.length,1);assert.equal(writes[0].path,'/fbpages_base_snapshot');assert.equal(writes[0].data.items.length,2,'both pages sharing an account reach shared storage');assert.equal(writes[0].data.schemaVersion,438);e.window.close();
 console.log('PASS: complete shared data repairs a collapsed local cache, no automatic source fetch, explicit refresh persists shared data');
})().catch(e=>{console.error(e);process.exit(1)});

