const assert=require('node:assert/strict'),fs=require('fs'),{JSDOM}=require('jsdom');
const source=fs.readFileSync('snippets/facebook-page-notifications-v1.js','utf8'),remote={};let writes=0;
function device(){const dom=new JSDOM('',{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w._rbUser={name:'Tester',role:'graphic'};w.fbGet=(p,cb)=>cb(null,JSON.parse(JSON.stringify(remote)));w.fbSet=async(p,v)=>{writes++;remote[p.split('/').pop()]=v;return true};w.rbFirebaseAuth={fetch:async(url,opts)=>{const key=new URL(url).pathname.split('/').pop().replace('.json','');if(opts.method==='PUT'){const data=JSON.parse(opts.body),ok=await w.fbSet('/'+key,data);return {ok,json:async()=>data};}return {ok:true,json:async()=>await new Promise(resolve=>w.fbGet('',(_,data)=>resolve(data)))};}};w.eval(source);return dom;}
(async()=>{const a=device(),b=device();try{const api=a.window.rbFacebookPageNotifications,other=b.window.rbFacebookPageNotifications,r={_fbpKey:'sheet_a',name:'Same name'},r2={_fbpKey:'sheet_b',name:'Same name'};
a.window.localStorage.setItem('rb_fb_notif',JSON.stringify({'Same name':'1'}));assert.equal(api.value(r),'1','legacy notification is preserved');
let resolve;a.window.fbSet=()=>new Promise(r=>resolve=r);const saving=api.save(r,'2');assert.equal(api.state(r).pending,true);assert.equal(api.value(r),'1','no success before acknowledgement');await Promise.resolve();resolve(false);assert.equal(await saving,false);assert.equal(api.state(r).error,true);
a.window.fbSet=async(p,v)=>{writes++;remote[p.split('/').pop()]=v;return true};a.window.Storage.prototype.setItem=()=>{throw Error('QuotaExceededError')};assert.equal(await api.save(r,'2'),true,'online save must survive cache exhaustion');assert.equal(api.value(r),'2');assert.equal(api.value(r2),'1','same-name pages remain independent');await other.pull();assert.equal(other.value(r),'2','another browser reads committed status');
assert.equal(await api.save(r,''),true);await other.pull();assert.equal(other.value(r),'','explicit reset overrides old legacy value');
let stale;a.window.fbGet=(p,cb)=>stale=cb;const reading=api.pull();await Promise.resolve();await api.save(r,'1');stale(null,{sheet_a:{value:'2'}});await reading;assert.equal(api.value(r),'1','old in-flight read cannot undo save');
Object.defineProperty(a.window.navigator,'onLine',{value:false,configurable:true});const before=writes;assert.equal(await api.save(r,'2'),false);assert.equal(writes,before,'offline selection must not claim an online write');assert.equal(api.state(r).error,true);Object.defineProperty(a.window.navigator,'onLine',{value:true});await Promise.all([api.save(r,'2'),api.save(r2,'1')]);await other.pull();assert.equal(other.value(r),'2');assert.equal(other.value(r2),'1','separate rows save independently');
a.window._rbUser={name:'Other',role:'viewer'};assert.equal(await api.save(r,'1'),false,'unapproved role cannot mutate');assert.equal(Object.keys(remote).length,2);
console.log('PASS notification acknowledgement, quota, offline/retry, concurrent rows, duplicate names, reset, stale reads and role/account boundary');
}finally{a.window.close();b.window.close();}})().catch(e=>{console.error(e);process.exitCode=1});
