const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('node:assert/strict');
(async()=>{const d=new JSDOM('<div id="cti-shared-history"></div>',{url:'https://example.test',runScripts:'outside-only'}),w=d.window;try{
let data={items:[{id:'ct_1750000000000_x',brand:'A',importBatch:'Old batch'}]},offline=false,lostAck=false;w.setTimeout=()=>0;w.clearTimeout=()=>{};w.ctCanManage=()=>true;w._ctData=[];w.localStorage.setItem('rb_ct_import_history_v1',JSON.stringify([{id:'stale',name:'Stale local'}]));w.Storage.prototype.setItem=function(){throw Error('quota')};w.fbGet=(p,cb)=>cb(offline?Error('offline'):null,data);w.rbFirebaseAuth={fetch:async(u,o={})=>{if(offline)throw Error('offline');if(o.method==='PUT'){data=JSON.parse(o.body);if(lostAck){lostAck=false;throw Error('lost ack')}}return{ok:true,headers:{get:()=> 'etag'},json:async()=>data}}};
w.eval(fs.readFileSync('snippets/import-history-v1.js','utf8'));w.eval(fs.readFileSync('snippets/performance-v4.js','utf8'));
await w.ctImportHistoryRefresh();assert(w.ctImportHistoryHtml().includes('Old batch'));assert(!w.ctImportHistoryHtml().includes('Stale local'));
const rec={id:'batch1',name:'New <batch>',count:1,brand:'A',createdAt:1760000000000};const row={id:'new',importBatchId:rec.id,importReceipt:rec};offline=true;await assert.rejects(w.ctPersistContent([row]));assert(w.ctImportHistoryHtml().includes('รอยืนยันออนไลน์'));offline=false;await w.ctSyncNow();assert.equal(data.importHistory.find(x=>x.id==='batch1').count,1);assert(w.ctImportHistoryHtml().includes('บันทึกออนไลน์แล้ว'));assert(w.ctImportHistoryHtml().includes('New &lt;batch&gt;'));
const r2={id:'new2',importBatchId:'batch2',importReceipt:{...rec,id:'batch2',name:'Concurrent'}};data.items.push(r2);data.importHistory.push(r2.importReceipt);lostAck=true;await assert.rejects(w.ctPersistContent([row]));await w.ctSyncNow();assert.equal(data.importHistory.filter(x=>x.id==='batch1').length,1);assert(data.importHistory.some(x=>x.id==='batch2'));await w.ctImportHistoryRefresh();assert(w.ctImportHistoryHtml().includes('Concurrent'));
const merged=w.ctImportHistoryMerge(data,[]);assert.equal(merged.find(x=>x.id==='batch1').remaining,0);assert(merged.some(x=>x.id==='batch2'));offline=true;await w.ctImportHistoryRefresh();assert(w.ctImportHistoryHtml().includes('ยังโหลดประวัติออนไลน์ล่าสุดไม่ได้'));w.ctCanManage=()=>false;assert.equal(await w.ctPersistContent([]),false);console.log('PASS cloud history: recovery, quota, offline/retry, lost acknowledgement, concurrent batch preservation, removal, escaping, role guard');
}finally{d.window.close()}})().catch(e=>{console.error(e);process.exitCode=1});
