const assert=require('node:assert/strict'),fs=require('fs'),{JSDOM}=require('jsdom');
const html=fs.readFileSync('index.html','utf8'),source=fs.readFileSync('snippets/leave-workforce-v1.js','utf8');
const dom=new JSDOM('<div id="lv-cal-body"></div><div id="lv-sum-inner"></div>',{runScripts:'outside-only'}),w=dom.window;
w.eval(html.slice(html.indexOf('var LV_EMPS='),html.indexOf('function lvOpenDay(')));
w.eval('function dk(y,m,d){return y+"-"+m+"-"+d} function iso(y,m,d){return y+"-"+String(m).padStart(2,"0")+"-"+String(d).padStart(2,"0")}'+source.slice(source.indexOf('function checkLeaveBatch('),source.indexOf('  function ordersFor(')));
const cycle=(...x)=>JSON.parse(JSON.stringify(w.lvGetCycle(...x)));
assert.deepEqual(cycle(2026,1,25),{endY:2026,endM:1});
assert.deepEqual(cycle(2026,1,26),{endY:2026,endM:2});
assert.deepEqual(cycle(2025,12,26),{endY:2026,endM:1});
assert.deepEqual(cycle(2028,2,29),{endY:2028,endM:3});
let uid=1;
function seed(dates,type='hol',empId='ter'){for(const date of dates)(w.LV_DATA[date]??=[]).push({uid:uid++,empId,type});}
w.LV_DATA={};seed(['2025-12-25','2025-12-26','2026-1-25','2026-1-26']);seed(['2026-1-10'],'vac');
assert.equal(w.lvCountHolCycle('ter',2026,1),2);
assert.equal(w.lvCountHolCycle('ter',2026,2),1);
assert.equal(w.lvCountVacYear('ter',2026),1);
w.LV_DATA={};seed(['2028-2-25','2028-2-26','2028-2-29','2028-3-25','2028-3-26']);
assert.equal(w.lvCountHolCycle('ter',2028,3),3);
const dates=(...days)=>days.map(d=>({y:2026,m:4,d}));
w.LV_DATA={};seed(['2026-4-1','2026-4-3','2026-4-5']);
const live=w.LV_DATA,before=JSON.stringify(live);
assert.ok(w.checkLeaveBatch('ter','hol',dates(8,10),'',null).some(x=>x.includes('วันหยุดรอบเต็ม')),'whole batch must count both proposed days');
assert.equal(w.LV_DATA,live);assert.equal(JSON.stringify(live),before,'preflight has no persistence side effects');
assert.equal(w.checkLeaveBatch('ter','hol',dates(8,26),'',null).length,0,'26th starts the next quota');
assert.equal(w.checkLeaveBatch('ter','hol',dates(8,10),'approved historical exception',null).length,0,'existing documented exception policy retained');
assert.ok(w.checkLeaveBatch('ter','hol',dates(5),'exception',null).some(x=>x.includes('มีรายการ')),'notes cannot bypass duplicates');
w.LV_DATA={};seed(['2026-4-1','2026-4-3','2026-4-5','2026-4-7']);
assert.equal(w.checkLeaveBatch('ter','hol',dates(9),'',{dateKey:'2026-4-7',entry:w.LV_DATA['2026-4-7'][0]}).length,0,'moving existing leave must not double count');
w.LV_DATA={};assert.ok(w.checkLeaveBatch('ter','hol',dates(10,11,12,13),'',null).some(x=>x.includes('ต่อกัน')),'consecutive checks see the whole batch');
w.LV_DATA={};seed(['2026-1-1','2026-2-1','2026-3-1','2026-4-1','2026-5-1'],'vac');
assert.ok(w.checkLeaveBatch('ter','vac',dates(10,12),'',null).some(x=>x.includes('พักร้อนครบ')));
w.LV_DATA={};seed(['2026-4-10'],'hol','jam');seed(['2026-4-10'],'hol','dom');
assert.ok(w.checkLeaveBatch('ter','hol',dates(10),'exception',null).some(x=>x.includes('ครบ 2 คน')),'notes cannot bypass staffing rules');
w.LV_DATA={'2026-4-7':[{uid:99,empId:'ter',type:'hol',note:'ลงย้อนหลังตามตารางเดิมรอบ ม.ค.–ก.ค. 2569'},{uid:100,empId:'dom',type:'hol',note:'หมายเหตุปกติ'}]};
w.LV_CUR={y:2026,m:4};w.lvRenderCal();
const chips=w.document.querySelectorAll('.lv-emp-chip');
assert.equal(chips[0].querySelector('.lv-chip-note'),null);assert.match(chips[0].title,/ลงย้อนหลัง/);
assert.ok(chips[1].querySelector('.lv-chip-note'));assert.match(w.LV_DATA['2026-4-7'][0].note,/ลงย้อนหลัง/);
dom.window.close();console.log('PASS cycle boundaries, projected batch quota/consecutive rules, edit accounting, note preservation');
