const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
(async()=>{let body='ชื่อบัญชี,พนักงาน,📌 แชร์บัญชีไหน\nAlpha,MOS,Shared A\nBeta,DOM,"One, Two"\nDuplicate,JAM,First\nDuplicate,JAM,Second\nBlank,TER,',failed=false,calls=0,renders=0;
const cache={},w={document:{getElementById(){return null}},localStorage:{getItem:k=>cache[k]||null,setItem(k,v){cache[k]=v}},fetch:async url=>{calls++;assert.equal(new URL(url).searchParams.get('tq'),'select G,C,V');if(failed)throw Error('offline');return{ok:true,text:async()=>body}},_lfbRender(){renders++}};w.window=w;vm.createContext(w);vm.runInContext(fs.readFileSync('snippets/list-facebook-editor.js','utf8'),w);w._lfbRender=()=>renders++;
assert.equal(await w._lfbLoadShares(),true);assert.equal(w._lfbSharedAccount({name:' Alpha ',emp:'MOSS'}),'Shared A');assert.equal(w._lfbSharedAccount({name:'Alpha',emp:'DOM'}),'');assert.equal(w._lfbSharedAccount({name:'Alpha',emp:'MOS',_source:'manual'}),'');assert.equal(w._lfbSharedAccount({name:'Duplicate',emp:'JAM'}),'');assert.equal(w._lfbSharedAccountHtml({name:'Blank',emp:'TER'}),'');assert.equal(w._lfbSharedAccount({name:'Beta',emp:'DOM'}),'One, Two');
await w._lfbLoadShares();assert.equal(calls,1);failed=true;assert.equal(await w._lfbLoadShares(true),false);assert.equal(w._lfbSharedAccount({name:'Alpha',emp:'MOS'}),'Shared A');
failed=false;body='ชื่อบัญชี,พนักงาน,📌 แชร์บัญชีไหน\nAlpha,MOS,\nBeta,DOM,<img src=x onerror=alert(1)>';
await w._lfbLoadShares(true);assert.equal(w._lfbSharedAccount({name:'Alpha',emp:'MOS'}),'');assert.ok(w._lfbSharedAccountHtml({name:'Beta',emp:'DOM'}).includes('&lt;img'));assert.ok(!w._lfbSharedAccountHtml({name:'Beta',emp:'DOM'}).includes('<img'));
body='wrong,columns';assert.equal(await w._lfbLoadShares(true),false);assert.ok(renders>=2);
console.log('PASS narrow source, name/staff matching, duplicates, manual isolation, refresh, offline, clear and escaping');})().catch(e=>{console.error(e);process.exitCode=1});
