const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const dom=new JSDOM('<div id="lfb-root"></div>',{url:'https://local.test',runScripts:'outside-only'});
const w=dom.window;
w.eval(fs.readFileSync('snippets/list-facebook-editor.js','utf8'));
const init=w._lfbInit;
w.eval(fs.readFileSync('snippets/list-facebook-followup.js','utf8'));
w.ctProductList=()=>['SYNBIOME','Blink Blink','JUDO'];
w._fpProdsCache=['JUDO','WOLF+'];
init();
w._listfbData=[{_key:'legacy',name:'Old account',emp:'Legacy Owner',prod:'Old Product'},{emp:'TER',prod:'judo'},{emp:'ter',prod:'JUDO'}];
const el=id=>w.document.getElementById(id);
const values=id=>Array.from(el(id).options,o=>o.value);
w._lfbOpenEditor('');
for(const key of ['emp','prod']){
 assert.equal(el('lfbe-'+key).tagName,'SELECT');
 assert.equal(el('lfbe-'+key).value,'','new accounts must not silently select first employee/product');
}
assert.ok(values('lfbe-prod').includes('SYNBIOME'),'products not yet used on accounts remain available');
assert.ok(values('lfbe-prod').includes('Blink Blink'));
assert.equal(values('lfbe-prod').filter(v=>v.toUpperCase()==='JUDO').length,1);
assert.equal(values('lfbe-emp').filter(v=>v.toUpperCase()==='TER').length,1);
w._lfbOpenEditor('legacy');
assert.equal(el('lfbe-emp').value,'Legacy Owner');
assert.equal(el('lfbe-prod').value,'Old Product');
w._lfbCloseEditor();
w.ctProductList=()=>['Fresh Product'];
w._lfbOpenEditor('');
assert.ok(values('lfbe-prod').includes('Fresh Product'),'reopening reads current catalog');
assert.equal(el('lfbe-prod').value,'');
const writes=[];
w.fbSet=(path,row)=>{writes.push({path,row});return Promise.resolve(true)};
el('lfbe-name').value='Dropdown fixture';
el('lfbe-emp').value='TER';
el('lfbe-prod').value='Fresh Product';
w._lfbSaveEditor();
assert.equal(writes.length,1);
assert.match(writes[0].path,/^\/listfacebook_manual\//);
assert.equal(writes[0].row.emp,'TER');
assert.equal(writes[0].row.prod,'Fresh Product');
assert.equal(writes[0].row.name,'Dropdown fixture');
dom.window.close();
console.log('PASS create/edit dropdowns, blank defaults, current catalogs, deduplication, legacy values and selected save payload');
