const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
(async()=>{
let offline=false,followOk=true;const remote={},cache={};const w={document:{getElementById(){return null}},localStorage:{getItem:k=>cache[k]||null,setItem(){throw Error('quota')}},_rbUser:{name:'Fixture'},fbGet(p,cb){cb(null,p==='/listfacebook_base_snapshot'?{schemaVersion:5,items:[{sourceRow:2,name:'A',emp:'TER'},{sourceRow:3,name:'B',emp:'DOM'}]}:p==='/listfacebook_edits'?remote:{})},fbSet:async(p,v)=>{if(offline)return false;remote[p.split('/').pop()]=JSON.parse(JSON.stringify(v));return true;},_lfbReconcileFollowupStatus:async()=>followOk};w.window=w;vm.createContext(w);vm.runInContext(fs.readFileSync('snippets/list-facebook-editor.js','utf8'),w);await w._listfbRefreshFromCloud();const a=w._listfbData[0]._key,b=w._listfbData[1]._key;
offline=true;assert.equal((await w._lfbSaveAccountRecord(a,{sharedAccount:'Retry share'})).online,false);assert.equal(w._lfbSharedAccount(w._listfbData[0]),'Retry share');assert.equal(Object.keys(remote).length,0);
offline=false;await Promise.all([w._lfbSaveAccountRecord(a,{sharedAccount:'A shared'}),w._lfbSaveAccountRecord(b,{sharedAccount:'B shared'})]);assert.equal(remote[a].sharedAccount,'A shared');assert.equal(remote[b].sharedAccount,'B shared');
followOk=false;assert.equal((await w._lfbSaveAccountRecord(a,{sharedAccount:'Partial'})).online,false);assert.equal(remote[a].sharedAccount,'Partial');followOk=true;assert.equal((await w._lfbSaveAccountRecord(a,{sharedAccount:'Partial'})).online,true);
await w._lfbSaveAccountRecord(a,{sharedAccount:''});await w._listfbRefreshFromCloud();assert.equal(w._lfbSharedAccount(w._listfbData[0]),'');assert.equal(w._lfbSharedAccount({_source:'manual',sharedAccount:'Manual'}),'Manual');assert.ok(w._lfbSharedAccountHtml({sharedAccount:'<script>'}).includes('&lt;script&gt;'));
await w._lfbSaveAccountRecord(a,{note:'unrelated edit'});assert.equal(remote[a].sharedAccount,'','unrelated saves preserve explicit blank');console.log('PASS sharing persistence: quota, offline retry, separate accounts, partial acknowledgement, clear, reload, escaping');
})().catch(e=>{console.error(e);process.exitCode=1});
