const fs=require('fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const dom=new JSDOM('<main></main><div><input id="om-prod" value="A"><input id="om-name" value="Title"><select id="om-hook"><option>H1</option></select><select id="om-hook2"><option>H2</option></select></div>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
const rows=[1,2,3,4].map(n=>({id:'row'+n,brand:'A',name:'Title',hook:'H'+n}));w.orderContentRows=()=>rows;w._rbUser={uid:'owner',name:'DOM',role:'graphic'};
let saved;w.ctSubmissions={readOwn:async()=>({etag:'0',value:null}),saveOwn:async(id,text)=>({etag:'1',value:{text}})};
for(const f of ['order-multiple-jobs','order-content-selection','order-list-content','employee-job-details'])w.eval(fs.readFileSync('snippets/'+f+'-v1.js','utf8'));
(async()=>{
const api=w.rbContentSelection;api.restore({hookExtra:['H3']});assert.equal(w.document.querySelector('.rb-extra-hook').value,'H3');w.document.querySelector('#om-add-hook').click();w.document.querySelectorAll('.rb-extra-hook')[1].value='H4';assert.equal(api.read().length,4);const order={id:'QA492',assignee:'DOM',product:'A',name:'Title',hook:'H1',hook2:'H2',hookExtra:Array.from(api.extra()),contentBindings:JSON.parse(JSON.stringify(api.read()))};api.restore(order);assert.deepEqual(Array.from(api.extra()),['H3','H4']);api.refresh(true,order.contentBindings);assert.equal(api.read()[3].id,'row4');
w.rbEmployeeJobDetails.mount(w.document.querySelector('main'),order,{rows:()=>rows,save:async fields=>{saved=fields;await w.rbOrderListContent.capture()();}});await new Promise(r=>setTimeout(r,0));const box=w.document.querySelector('#rb-employee-job-details');assert.equal(box.querySelectorAll('.olc-card').length,4);const input=box.querySelector('[aria-label="List Content ของ HOOK 4"]');input.value='Fourth content';input.dispatchEvent(new w.Event('input'));await Array.from(box.querySelectorAll('button')).find(b=>b.textContent==='บันทึกข้อมูลและ List Content').onclick();assert.deepEqual(Array.from(saved.hookExtra),['H3','H4']);assert.equal(saved.contentBindings[3].id,'row4');w.dispatchEvent(new w.Event('rb:content-updated'));assert.equal(input.value,'Fourth content');box.querySelector('[aria-label="ลบ HOOK"]').click();assert.deepEqual(Array.from(w.rbEmployeeJobDetails.read(order).hookExtra),['H4']);assert.equal(box.querySelector('[aria-label="List Content ของ HOOK 3"]').value,'Fourth content');w._rbUser={uid:'other',name:'TER',role:'graphic'};assert.equal(w.rbEmployeeJobDetails.read(order),null);dom.window.close();console.log('PASS multi-HOOK supervisor restore, employee selection, source IDs, List Content, removal, refresh and role guards');
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1});
