const fs=require('fs');const assert=require('assert');
const index=fs.readFileSync('index.html','utf8');
assert.ok(index.includes("var _isView=!!id&&window._ordViewMode==='team'"),'team view mode must only lock an existing order, never a new order');
assert.ok(index.includes("_omSaveBtn.textContent=_omIsNew?'▤ สั่งงาน':'▤ บันทึกงาน'"),'editable Supervisor forms must expose the correct new/edit action');
assert.ok(index.includes("_omSaveBtn.onclick=saveOM2"),'the order action must save through the normal order workflow');
assert.ok(index.includes("ab.id='ord-add-btn'")&&index.includes('window.openOM(null)'),'Add new order must open a genuinely new order');
assert.ok(index.includes("ge('om-st').value=o?(o.status||''):'pending'"),'new Supervisor orders must start in assigned status');
assert.ok(index.includes("setOMSubmitFeedback('กำลังบันทึกงาน...','success')"),'the sticky footer must show save progress');
assert.ok(index.includes('<meta name="rb-build" content="fix269">'));
console.log('order-new-supervisor-v1: all tests passed');
