const assert=require('node:assert/strict');
const fs=require('node:fs');

const index=fs.readFileSync('index.html','utf8');
const workflow=fs.readFileSync('snippets/order-audit-version-workflow-v1.js','utf8');
const persistence=fs.readFileSync('snippets/order-audit-persistence-v1.js','utf8');
const css=fs.readFileSync('snippets/order-audit-version-workflow-v1.css','utf8');

assert.ok(index.includes('order-audit-version-workflow-v1.css?v=fix350'),'the unified version layout must be cache-busted');
assert.ok(index.includes('order-audit-version-workflow-v1.js?v=fix350'),'the unified version runtime must be cache-busted');
assert.ok(workflow.includes("return current==='sup'||current==='audit'"),'Supervisor and Audit must be able to record audit results');
assert.ok(workflow.includes("current==='graphic'||current==='spec'"),'Graphic and Specialist employees must receive the correction view');
assert.ok(workflow.includes("kind==='image'?'#om-image-submitlinks-rows"),'image delivery links must be read from the send-work editor');
assert.ok(workflow.includes(":'#om-submitlinks-rows .om-submitlink-row input'"),'ad delivery links must be read from the send-work editor');
assert.ok(workflow.includes('workLink:workLink,imageLink:imageLink'),'each VER must persist both delivery link types');
assert.ok(workflow.includes("fixLink:String(old.fixLink||'')"),'a corrected link must be stored separately from the original submitted link');
assert.ok(workflow.includes("buildSection(teamPanel,'rb-team-version-workflow'"),'the send-image tab must receive the synchronized team view');
assert.ok(workflow.includes("buildSection(auditPanel,'rb-audit-version-workflow'"),'the Audit tab must receive the same shared version state');
assert.ok(workflow.includes('แก้เฉพาะข้อมูลและหลักฐานของเวอร์ชันนี้'),'employees must be told that corrections are version-specific');
assert.ok(workflow.includes('สิ่งที่ Audit พบ'),'the team view must show Audit findings');
assert.ok(workflow.includes('ลากรูปมาวาง หรือกดเลือกไฟล์'),'employee evidence uploads must offer a clear multi-image drop zone');
assert.ok(workflow.includes("current==='graphic'&&canonicalName(order&&order.assignee)===canonicalName(actor())"),'Graphic users must only submit corrections for their own assigned work');
assert.ok(workflow.includes("current==='sup'||current==='spec'"),'Supervisor and Specialist must be able to assist with correction submissions');
assert.ok(workflow.includes("auditMode=canAudit()?'audit':'readonly'"),'Audit editing must remain separate from employee correction permissions');
assert.ok(workflow.includes("teamMode=canSubmitCorrection(order)?'employee':'readonly'"),'the correction area must calculate its own permission mode');
assert.ok(workflow.includes('state.fixNote=this.value'),'employee correction notes must persist per version');
assert.ok(workflow.includes('state.fixLink=this.value'),'employee correction links must persist per version without replacing the audited source in memory');
assert.ok(workflow.includes('employeeSubmittedAt'),'the workflow must distinguish new corrections waiting for Audit');
assert.ok(workflow.includes('Promise.resolve(typeof window.spORD'),'employee correction saves must wait for durable persistence');
assert.ok(workflow.includes('if(!section||section._rbSaving)return'),'rapid repeated clicks must not create duplicate correction submissions');
assert.ok(workflow.includes('var orders=clone(typeof window.lpORD'),'a failed online save must not mutate the current order cache in place');
assert.ok(workflow.includes("setMessage(document.getElementById('rb-team-version-workflow'),successMessage)"),'save confirmation must remain visible after the synchronized view rerenders');
assert.ok(workflow.includes("source:'version-audit-correction'"),'employee corrections must append a durable revision history entry');
assert.ok(workflow.includes('order.latestRevisionImageLinks=clone(imageLinks)'),'the latest corrected image links must reopen after refresh');
assert.ok(workflow.includes('state.correctionRequestedAt=now+index'),'a new Audit correction round must be marked explicitly per version');
assert.ok(workflow.includes('correctionDraftUpdatedAt<=state.correctionRequestedAt'),'an older correction must not be resubmitted as if it were new');
assert.ok(workflow.includes('window.rbValidateAuditVersionDecision'),'overall Audit decisions must validate version-level results');
assert.ok(index.includes("rbValidateAuditVersionDecision('issue')"),'return-for-correction must apply the overall Audit decision');
assert.ok(index.includes("rbValidateAuditVersionDecision('pass')"),'completion must apply the overall Audit decision');
assert.ok(workflow.includes("if(!issues.length&&populated.length)"),'needs-revision must automatically target the latest populated VER when Audit leaves the optional detail blank');
assert.ok(workflow.includes("if(kind==='pass')populated.forEach"),'complete must mark populated versions passed without forcing every Audit field to be filled');
assert.ok(!workflow.includes('ยังมีเวอร์ชันที่ไม่ผ่าน:'),'an old per-version result must not block the overall complete button');
assert.ok(workflow.includes('auditImages:Array.isArray(old.auditImages)'),'Audit evidence must persist per version');
assert.ok(workflow.includes('fixImages:Array.isArray(old.fixImages)'),'employee evidence must persist per version');
assert.ok(workflow.includes("item.versionKey=versionKey(id,index+1)"),'each saved version must be owned by job id and VER');
assert.ok(workflow.includes('if(!itemJob&&!itemKey)owned=sameSource(item,values[version-1])'),'legacy state must not leak into unrelated jobs');
assert.ok(persistence.includes('workflowJob===orderJob'),'saving must never copy a visible Audit panel into another job');
assert.ok(persistence.includes('order.auditVersions=window.rbCollectAuditVersionWorkflow(workflow)'),'the shared version state must save with the order');
assert.ok(workflow.includes("submitted.className='rb-av-stage rb-av-stage-source'"),'submitted work must live in the VER header area');
assert.ok(workflow.includes('head.appendChild(submitted)'),'submitted work must be placed directly under the VER name');
assert.ok(workflow.includes('flow.append(audit,teamCorrection'),'the lower team workflow must contain only Audit findings and correction submission');
assert.ok(css.includes('.rb-av-flow{display:grid;grid-template-columns:1.18fr 1fr}'),'desktop team workflow must show Audit findings beside correction submission');
assert.ok(css.includes('@media(max-width:900px)'),'the two-stage workflow must stack on smaller screens');
assert.ok(css.includes('.surface-team'),'the team surface must have a clear synchronized workspace');
assert.ok(!index.includes("fixHdrP1.textContent='✅ รูปงานที่แก้ไขแล้ว'"),'the duplicate global employee correction uploader must be removed');
assert.ok(!index.includes("revImgSection.id='om-rev-imgs'"),'the duplicate global Audit evidence uploader must be removed');
assert.ok(index.includes('order.errorImages=JSON.parse(JSON.stringify(_omErrorImages||[]))'),'legacy Audit images must remain in persistence for backward compatibility');
assert.ok(index.includes('order.fixImages=JSON.parse(JSON.stringify(_omFixImages||[]))'),'legacy corrected images must remain in persistence for backward compatibility');
assert.ok(workflow.includes("option.textContent='✓ อัพแล้ว'"),'uploaded source data must keep its explicit green status');
assert.ok(workflow.includes('window.rbSyncAuditSourceStatus=syncSourceStatus'),'the source status refresher must remain callable');
assert.ok(workflow.includes('rb-av-audit-title-row'),'the Audit card must have a clear VER title row');
assert.ok(workflow.includes('rb-av-audit-source-row'),'submitted work must be separated from the Audit decision controls');
assert.ok(workflow.includes("field('ผลตรวจ',result"),'Audit decision controls must have persistent visible labels');
assert.ok(css.includes('.surface-audit .rb-av-audit-fields{grid-template-columns:'),'the redesigned Audit form must use an orderly desktop grid');
assert.ok(css.includes('@media(max-width:980px)'),'the redesigned Audit form must adapt to medium screens');
assert.ok(css.includes('@container audit-workspace (max-width:760px)'),'the redesigned Audit form must adapt to the modal content width');
assert.ok(css.includes('#rb-order-modal .rb-om-window{max-width:1120px'),'all three workflow tabs must keep the same desktop width');
assert.ok(!css.includes('[data-active-tab="links"] .rb-om-window'),'tab switching must not change the modal width');

console.log('order-audit-version-workflow-v1: all tests passed');
