const fs=require('fs');
const assert=require('assert');
const vm=require('vm');
const index=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('snippets/order-planner-v1.js','utf8');
const css=fs.readFileSync('snippets/order-planner-v1.css','utf8');

assert.ok(index.includes('<meta name="rb-build" content="fix305-del">'),'build marker must expose fix305');
assert.ok(index.includes('#rb-dd-popover{position:fixed;z-index:100200;'),'planner DropDown popover must render above the planner modal');
assert.ok(index.includes('snippets/order-planner-v1.css?v=fix303'),'planner stylesheet must be loaded');
assert.ok(index.includes('snippets/order-planner-v1.js?v=fix305'),'planner script must be loaded');
assert.ok(js.includes("user()&&user().role==='sup'"),'planner access must be limited to Supervisor');
assert.ok(js.includes("if(!isSupervisor())return false"),'planner API must reject non-Supervisor users');
assert.ok(css.includes('body.rb-not-sup #ord-planner-btn{display:none!important}'),'planner entry button must stay hidden for every non-Supervisor role');
assert.ok(js.includes("CLOUD='/order_planner/drafts'"),'multiple drafts must sync through a dedicated shared path');
assert.ok(js.includes('function reserveIds(')&&js.includes('function dispatchDraft('),'scheduled jobs must reserve ids and use the automatic dispatch workflow');
assert.ok(js.includes("sourceDraftId:d.id")&&js.includes("autoDispatched:true"),'automatic orders must be traceable to one exact draft');
assert.ok(js.includes("orderKey='planner_'+cloudKey(d.id)"),'automatic dispatch must use an idempotent per-draft database key');
assert.ok(js.includes("if(!/^GR\\d+$/.test(id))return"),'draft timestamps must never be mistaken for visible GR order numbers');
assert.ok(js.includes("typeof window.lvGetDay!=='function'")&&js.includes('function chooseAssignee('),'automatic assignment must check the existing leave calendar');
assert.ok(js.includes("d.repeat==='weekly'")&&js.includes("d.repeat==='none'"),'weekly and monthly recurring plans must be supported');
assert.ok(js.includes('setInterval(function(){if(window._rbUser)runWorker()},60000)'),'the dashboard must continuously check scheduled work');
assert.ok(js.includes("window.addEventListener('online'"),'overdue work must be checked again when the dashboard reconnects');
assert.ok(js.includes('บันทึกฉบับร่างทั้งหมด')&&js.includes('ตั้งเวลางานที่เลือก')&&js.includes('สั่งงานที่เลือกตอนนี้'),'bulk draft actions must be present');
assert.ok(js.includes('ตารางแพลนงาน')&&js.includes('กฎสั่งงานอัตโนมัติ'),'planner and automation views must be present');
assert.ok(js.includes('rbp-drafts-layout')&&js.includes('rbp-draft-list')&&js.includes('rbp-detail-editor'),'draft creation must use the approved left-list and right-form layout');
assert.ok(js.includes("brief:d.brief||''")&&js.includes("sampleLink:d.sampleLink||''")&&js.includes("rawLink:d.rawLink||''")&&js.includes("sheetLink:d.sheetLink||''"),'drafts must retain the full brief and reference-link set');
assert.ok(js.includes("brief:d.brief||''")&&js.includes("hook:d.hook||''")&&js.includes("hook2:d.hook2||''")&&js.includes("note:d.note||''"),'automatic orders must inherit all one-time detail fields');
assert.ok(js.includes('กรอกครั้งเดียว')&&js.includes('ตรวจออดิต')&&js.includes('ส่งงานภาพ'),'the planner must explain the one-entry synchronization flow');
assert.ok(js.includes('function queueAutosave(')&&js.includes('บันทึกในเครื่องแล้ว · รอซิงก์')&&js.includes('บันทึกและซิงก์แล้ว'),'autosave must distinguish pending local data from confirmed cloud sync');
assert.ok(js.includes('window.rbPersistence.related(CLOUD)'),'pending planner writes must block stale cloud data from replacing local drafts');
assert.ok(js.includes('function renderDraftsV3(')&&js.includes('ฟอร์มด้านขวาใช้ช่องและพฤติกรรมเดียวกับ “เพิ่มงานใหม่”'),'the right-side editor must expose the Add New parity form');
assert.ok(js.includes("workStatus:d.workStatus||'pending'")&&js.includes("status:d.workStatus||'pending'"),'the planner must retain the selected Add New work status');
assert.ok(js.includes('BRIEF_PRESETS')&&js.includes('data-action="toggle-presets"')&&js.includes('data-action="apply-preset"'),'the Add New brief preset workflow must be available');
assert.ok(js.includes('data-upload="brief"')&&js.includes('function handlePlannerFileChange('),'sample-image upload must work from the planner form');
assert.ok(js.includes('function plannerContentRows(')&&js.includes('function applyPlannerContent('),'Content Tracker suggestions must populate the same Hook and reference-link fields');
assert.ok(js.includes("'contentChoice'")&&js.includes('function plannerJobs('),'the planner must expose a visible Content Tracker DropDown instead of a hidden datalist');
assert.ok(js.includes("window.refreshOrderContentFromCloud")&&js.includes('content.then(function()'),'opening the planner must refresh Content Tracker before rebuilding its DropDowns');
assert.ok(js.includes('function applyPlannerProductAssets(')&&index.includes('window._rbProductAssetLinks=PRODUCT_ASSET_LINKS'),'product Footage and Insert / Review links must share the Add New catalog');
assert.ok(js.includes("if(field==='hook'){applyPlannerContent(d,true)"),'each Hook/version must populate only its matching Content Tracker links');
assert.ok(js.includes('assignmentDate=d.deadline||d.scheduledDate')&&js.includes('leaveCodes(assignmentDate)'),'automatic assignment must use the Add New Deadline for leave checks');
assert.ok(js.includes('ลิงก์ตัวอย่าง/ลิงก์รายละเอียดงาน')&&js.includes('ลิงก์ไฟล์ดิบ (Creative)')&&js.includes('ลิงก์สคริปต์'),'the complete Add New reference-link set must be present');
assert.ok(js.includes('data-status-filter="draft"')&&js.includes('data-status-filter="scheduled"')&&js.includes('data-status-filter="blocked"'),'the summary cards must filter each status independently');
assert.ok(js.includes('data-planner-date-filter="1"')&&js.includes('data-action="select-all-visible"'),'the left list must include a Deadline filter and select-all-visible control');
assert.ok(css.includes('.rbp-list-filter-row')&&css.includes('.rbp-select-visible'),'date and select-all controls must have planner styling');
assert.ok(js.includes('4. งานที่สั่งแล้ว')&&js.includes('function renderHistory('),'the planner must include a dispatched-work history view');
assert.ok(js.includes('data-action="open-history-delete"')&&js.includes('data-history-delete-check')&&js.includes('data-action="confirm-history-delete"'),'deleting a dispatched job must require an explicit checked confirmation');
assert.ok(js.includes("className='rbp-history-delete rbp-draft-delete'")&&js.includes("setAttribute('data-action','delete')")&&js.includes('ลบรายการนี้'),'tab 1 must expose a guarded delete action for the selected draft');
assert.ok(js.includes("deleteJSON('/orders/'+remoteKey)")&&js.includes('function removeDispatchedDraft('),'confirmed deletion must remove the exact planner order and its history draft');
assert.ok(js.includes('HOOK 2 (ถ้ามี)')&&js.includes('data-field="hook2"'),'the planner parity form must expose a second optional Hook');
assert.ok(css.includes('.rbp-history-layout')&&css.includes('.rbp-history-delete-overlay'),'history and destructive confirmation must have responsive planner styling');

const sandbox={window:{_rbUser:{name:'View',role:'sup'},addEventListener(){}},document:{readyState:'loading',addEventListener(){}},localStorage:{getItem(){return null},setItem(){}},console,Date,JSON,Object,Array,String,Number,Math,Promise,setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},fetch(){return Promise.resolve({ok:true,json(){return Promise.resolve({})}})}};
vm.runInNewContext(js,sandbox);
const filter=sandbox.window._rbOrderPlannerTest;
const sample=[{id:'1',status:'draft',deadline:'2026-08-29'},{id:'2',status:'scheduled',deadline:'2026-08-29'},{id:'3',status:'scheduled',deadline:'2026-08-30'},{id:'4',status:'blocked',deadline:'2026-08-30'},{id:'5',status:'dispatched',deadline:'2026-08-30'}];
assert.deepStrictEqual(Array.from(filter.filterByStatus(sample,'scheduled'),x=>x.id),['2','3'],'scheduled filter must not include drafts or blocked work');
assert.deepStrictEqual(Array.from(filter.filterByStatus(sample,'all'),x=>x.id),['1','2','3','4'],'the active-work list must exclude dispatched history rows');
assert.deepStrictEqual(Array.from(filter.filterByDate(sample,'2026-08-30'),x=>x.id),['3','4','5'],'date filter must match the visible Deadline exactly');
assert.strictEqual(filter.plannerOrderMatches({sourceDraftId:'draft-a',id:'GR090'},{id:'draft-a',orderId:'GR090'}),true,'history deletion must match the order by exact source draft id');
assert.strictEqual(filter.plannerOrderMatches({sourceDraftId:'draft-b',id:'GR091'},{id:'draft-a',orderId:'GR090'}),false,'history deletion must never match a different job');
console.log('order-planner-v1: all tests passed');
