const fs=require('fs');
const assert=require('assert');
const source=fs.readFileSync('index.html','utf8');
const theme=fs.readFileSync('snippets/order-modal-graphite-teal-v1.css','utf8');

assert(source.includes('snippets/order-modal-graphite-teal-v1.css'), 'Graphite Teal stylesheet is not loaded');
assert(theme.includes('html:not([data-theme=dark]) #rb-order-modal .rb-om-header{background:#22333c!important}'), 'Graphite Teal modal theme is missing');
assert(source.includes('.rb-revision-ref-copy'), 'reference-link copy control styles are missing');
assert(source.includes('function revisionCopyUrl(url,button)'), 'reference-link copy behavior is missing');
assert(source.includes('revisionImageGroup(order)'), 'all uploaded order images must render in the combined image gallery');
assert(source.includes("['briefImages','รูปตัวอย่าง'],['images','รูปส่งงาน'],['errorImages','รูปข้อผิดพลาด'],['fixImages','รูปแก้ไข']"), 'combined image gallery must include every image category');
assert(source.includes("revisionUniformLinkRows('ลิงก์ตัวอย่าง/ลิงก์รายละเอียดงาน',[order.sampleLink]"), 'sample/detail URL must remain a separate link field');
assert(source.includes("title.textContent='รวมภาพ'"), 'combined image gallery title is missing');
assert(source.includes("empty.textContent='ยังไม่มีภาพในงานนี้'"), 'empty combined gallery state is missing');
assert(source.includes("revisionUniformLinkRows('ลิงก์คลิป',clipLinks"), 'clip links are missing from detail view');
assert(source.includes("revisionUniformLinkRows('ลิงก์งาน',workLinks"), 'work links are missing from detail view');
assert(source.includes("revisionUniformLinkRows('FOOTAGE',[order.footageLink].concat(productAssets.footage||[])"), 'Footage links must remain and be deduplicated');
assert(source.includes("revisionUniformLinkRows('INSERT / REVIEW',[order.reviewLink].concat(productAssets.review||[])"), 'Insert / Review links must remain and be deduplicated');
assert(source.includes("value.replace(/[?#].*$/,'').replace(/\\/+$/,'').toLowerCase()"), 'equivalent Drive links with query strings must be deduplicated');
assert(source.includes("var alwaysNumber=label==='FOOTAGE'||label==='INSERT / REVIEW'"), 'Footage and review links must always use numbered labels');
assert(source.includes('snippets/order-detail-unified-v1.css'), 'unified detail link stylesheet is not loaded');
assert(source.includes("sv.setAttribute('data-rb-leading-icon','1')"), 'sticky save icon must be protected from the global icon converter');
assert(source.includes('m5 12 4 4L19 6'), 'sticky header check icon is missing');
assert(source.includes('var _structuredDetailView=!!o'), 'structured detail must be shown for every existing job and every user role');
assert(source.includes("var canEditOriginal=role==='sup'||role==='spec'"), 'Supervisor and Specialist must retain an explicit edit mode');
assert(source.includes("edit.innerHTML='<span aria-hidden=\"true\">✎</span><b>แก้ไขข้อมูล</b>'"), 'structured manager view must expose the edit-mode control');
assert(source.includes("_OM2.classList.add('rb-revision-edit-mode')"), 'manager edit mode must preserve the original editable form');
assert(source.includes('snippets/order-detail-all-users-v1.css'), 'all-user structured detail stylesheet is not loaded');
assert(source.includes("if(order.status==='revision')"), 'revision warning must only appear for revision jobs');
assert(source.includes("statusLabels={pending:'มอบหมาย',inprogress:'กำลังดำเนินการ',review:'รอตรวจ',revision:'ต้องแก้ไข',done:'เสร็จสมบูรณ์'}"), 'structured detail must show the actual workflow status');
assert(source.includes("var workIds=['om-p1fix-hdr','om-p1fix-gallery','om-p1fix-wrap','om-p1fix-inp','om-submitlinks-section']"), 'team workspace must contain only fix-image and current submission controls');
assert(source.includes("<small>อัปโหลดรูปแก้ไข • เพิ่มลิงก์ส่งงาน</small>"), 'team workspace subtitle must match the visible controls');
assert(source.includes(':not(#rb-revision-team-workspace)'), 'team submit-link workspace must remain editable');
assert(source.includes("teamWorkspace.id='rb-revision-team-workspace'"), 'team edit controls must stay grouped in one workspace');

console.log('order detail Graphite Teal tests passed');
