const assert=require('node:assert/strict'),fs=require('fs'),{JSDOM}=require('jsdom'),vm=require('vm');
const dom=new JSDOM('<div id="om-submit-feedback"></div>',{runScripts:'outside-only'}),w=dom.window;
w._rbUser={name:'DOM',role:'graphic'};w._renderSubmitLinkRows=()=>{};w._renderImageSubmitLinkRows=()=>{};w.lpORD=()=>[];
w.eval(fs.readFileSync('snippets/personal-test-work-v1.js','utf8'));const api=w.rbPersonalWork;
w.document.body.insertAdjacentHTML('beforeend','<section id="rb-employee-job-details"></section>');api.begin(null,true);assert.equal(w.document.getElementById('rb-employee-job-details'),null);api.restore({rows:[{fbName:'A',pageName:'Page A',name:'Camp A',link:'https://example.test/a'},{fbName:'B',pageName:'Page B',name:'Camp B',link:'https://example.test/b'}],sharedLink:'https://example.test/shared',deadline:'2026-10-22',note:'test'});
assert.equal(api.sources({})[1].fbName,'B');assert.equal(api.sources({})[1].workLink,'https://example.test/b');assert.equal(api.sources({})[0].imageLink,api.sources({})[1].imageLink);
assert.equal(api.prepare(),true);const entry={id:'GR_QA',status:'review',submitLinks:['a','b'],imageSubmitLinks:['shared']};api.persist(entry);assert.equal(entry.type,'เทสส่วนตัว');assert.equal(entry.personalCampaigns.length,2);assert.equal(entry.reviewRounds.events.length,1);assert.ok(entry.firstSubmittedAt);assert.equal(entry.reviewRounds.complete,true);
const owned={...entry,assignee:'DOM',status:'inprogress',_fbKey:'qa'};api.begin(owned);w.lpORD=()=>[{...owned,status:'review'}];assert.equal(api.prepare(),false,'stale status blocks overwrite');w._rbUser={name:'BALL',role:'graphic'};api.begin(owned);assert.equal(api.canSubmit(),false);assert.equal(api.prepare(),false);w._rbUser={name:'QA',role:'audit'};assert.equal(api.allowed(),false);assert.throws(()=>api.begin(null,true));api.begin({id:'normal'});assert.equal(api.active(),false);dom.window.close();
// Same order-based deduction rules, without introducing a separate charge path.
const orders=[];const win={addEventListener(){},lpORD(){return orders;},_rbUser:{name:'QA',role:'sup'}};const document={documentElement:{},body:{appendChild(){}},querySelector(){return null;},querySelectorAll(){return[];},createElement(){return{remove(){},dataset:{}};}};
vm.runInNewContext(fs.readFileSync('snippets/deduction-reset-policy-v1.js','utf8')+'\n'+fs.readFileSync('snippets/audit-deduction-center-v1.js','utf8'),{window:win,document,localStorage:{getItem(){return null;},setItem(){}},MutationObserver:class{observe(){}},setTimeout(){},fetch(){throw Error('No network expected');},Date,Math,JSON,Object,Array,String,Number,Promise,Error,RegExp,isNaN});
const t=new Date(2026,9,5,9).getTime();const base={id:'QA_MAIN',_fbKey:'main',name:'QA',assignee:'DOM',status:'revision',deadline:'2026-10-01',auditVersions:[{version:1,result:'issue',correctionRequestedAt:t}]};orders.push(base,{...base,id:'QA_PERSONAL',_fbKey:'personal',type:'เทสส่วนตัว',personalTest:true});const found=win._rbAuditDeductionTest.detectOrders(t+86400000*4);const main=found.filter(x=>x.orderId==='QA_MAIN'),personal=found.filter(x=>x.orderId==='QA_PERSONAL');assert.ok(main.length>0);assert.equal(personal.length,main.length);assert.deepEqual(personal.map(x=>[x.ruleId,x.amount]),main.map(x=>[x.ruleId,x.amount]));
console.log('Personal tests: version identity, shared URL, tracked first submission, ownership/stale guard and identical deduction rules passed');
