const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const ctx={window:{},Response};vm.createContext(ctx);vm.runInContext(fs.readFileSync('snippets/safe-order-write-v1.js','utf8'),ctx);
const api=ctx.window.rbSafeOrderWrite;
const remote={id:'TEST',status:'review',updatedAt:30,_version:3,submitLink:'https://example.com/work',nested:{a:1,b:2}};
assert(api.matches(remote,{status:'review',submitLink:remote.submitLink,updatedAt:20,_version:2},'PATCH'));
assert(api.matches(remote,{nested:{b:2,a:1}},'PATCH'));
assert(!api.matches(remote,{status:'pending',updatedAt:40},'PATCH'));
assert(!api.matches(remote,{submitLink:'https://example.com/other'},'PATCH'));
assert(!api.matches(remote,{updatedAt:40},'PATCH'));
assert(!api.matches(remote,{id:'TEST',status:'review'},'PUT'));
assert(!api.matches({...remote,_deleted:true},{status:'review'},'PATCH'));
assert(!api.matches(remote,{status:'review',submitLink:null},'PATCH'));
const source=fs.readFileSync('index.html','utf8');
const fn=source.slice(source.indexOf('function fbApplyRemoteOrders(data){'),source.indexOf('var _fbRecentOrderWrites=',source.indexOf('function fbApplyRemoteOrders(data){')));
let queue=[{token:'old',path:'/orders/test',method:'PATCH',data:{status:'review',updatedAt:20},conflict:true},{token:'real-conflict',path:'/orders/test',method:'PATCH',data:{status:'pending'},conflict:true}];
Object.assign(ctx,{fbOrderQueueLoad:()=>queue,fbOrderQueueSave:q=>queue=q,_fbRecentOrderWrites:{},lpORD:()=>[],fbMergeRemoteSnapshot:()=>[],localStorage:{setItem(){}},LS_ORD:'orders',refreshOrderViews(){}});
vm.runInContext(fn,ctx);ctx.fbApplyRemoteOrders({test:remote});assert.equal(queue.length,1);assert.equal(queue[0].token,'real-conflict');
(async()=>{let writes=0;const request=async(u,o)=>{if(o.method)writes++;return new Response(JSON.stringify(remote),{headers:{ETag:'version'}});};
await api.write('test',{method:'PATCH',body:JSON.stringify({status:'review',updatedAt:20}),rbBaseUpdatedAt:10},request);assert.equal(writes,0);
await assert.rejects(()=>api.write('test',{method:'PATCH',body:JSON.stringify({status:'pending',updatedAt:40}),rbBaseUpdatedAt:10},request));assert.equal(writes,0);
console.log('PASS: equivalent receipts clear without writes; true conflicts, missing fields, deletion, and stale rollback remain protected');})();
