const fs=require('fs');const assert=require('assert');
const js=fs.readFileSync('snippets/unified-graphic-headers-v1.js','utf8');
const css=fs.readFileSync('snippets/unified-graphic-headers-v1.css','utf8');
const index=fs.readFileSync('index.html','utf8');
['order','links','commission','audit','fblist','idcard'].forEach(k=>assert.ok(js.includes(k+':{'),`missing ${k} header config`));
assert.ok(js.includes("key==='listfb'"),'List Facebook must be explicitly excluded');
assert.ok(css.includes('[data-sub="listfb"] .rb-unified-section-banner{display:none!important}'),'CSS must also protect List Facebook');
assert.ok(!js.includes('rb-unified-original-action')&&!css.includes('rb-unified-original-action'),'existing functional buttons must remain visible and untouched');
assert.ok(!js.includes('live.click()'),'the presentation module must not proxy or replace existing button behavior');
assert.ok(index.includes("ab.id='ord-add-btn'")&&index.includes("window.openOM(null)"),'the original Add new order button must continue opening the order form directly');
['localStorage','fbSet(','fetch(','removeItem(','innerHTML=\'\''].forEach(s=>assert.ok(!js.includes(s),`presentation module must not mutate app data: ${s}`));
['order','links','commission','audit','fblist','idcard'].forEach(k=>assert.ok(css.includes(`.gsp.gsp-active[data-sub="${k}"]`),`missing spacing for ${k}`));
assert.ok(!css.includes('.gsp.gsp-active[data-sub="listfb"]'),'List Facebook spacing/layout must remain untouched');
assert.ok(css.includes('grid-template-columns:repeat(4,minmax(0,1fr))'),'desktop summaries must use a four-column grid');
assert.ok(css.includes('.rb-unified-graphic-section[data-sub="order"] #ord-stats'),'the order summary must use the shared grid without changing its live cards');
assert.ok(!css.includes('>*:not(.rb-unified-section-banner)'),'existing content spacing must not be rewritten');
assert.ok(index.includes('rb-fbp-summary-grid')&&index.includes("['start','ต้องเริ่มแก้'")&&index.includes("['fixed','แก้แล้ว'"),'Facebook Pages must have the second follow-up summary row');
assert.ok(index.includes('window._fbRefreshPageSummary'),'Facebook Pages follow-up totals must refresh after status changes');
assert.ok(index.includes('snippets/unified-graphic-headers-v1.css?v=230'));
assert.ok(index.includes('snippets/unified-graphic-headers-v1.js?v=266'));
assert.ok(js.includes("title:'สั่งงาน Graphic'")&&js.includes("title:'รวมลิงก์ Content'")&&js.includes("title:'จัดการ Facebook Pages'"),'page titles must omit the word ศูนย์');
assert.ok(!js.includes("title:'ศูนย์"),'unified page titles must not retain the word ศูนย์');
assert.ok(index.includes('<meta name="rb-build" content="fix288-send-image-ver-layout">'));
assert.ok(index.includes('<div class="ct-title">Content Tracker')&&!index.includes('OLYMPPLUS Content Tracker'),'the Links title must omit the OLYMPPLUS prefix');
console.log('unified-graphic-headers-v1: all tests passed');
