const fs=require('fs');const assert=require('assert');
const js=fs.readFileSync('snippets/unified-graphic-headers-v1.js','utf8');
const css=fs.readFileSync('snippets/unified-graphic-headers-v1.css','utf8');
const index=fs.readFileSync('index.html','utf8');
['order','links','commission','audit','fblist','idcard'].forEach(k=>assert.ok(js.includes(k+':{'),`missing ${k} header config`));
assert.ok(js.includes("key==='listfb'"),'List Facebook must be explicitly excluded');
assert.ok(css.includes('[data-sub="listfb"] .rb-unified-section-banner{display:none!important}'),'CSS must also protect List Facebook');
assert.ok(!js.includes('rb-unified-original-action')&&!css.includes('rb-unified-original-action'),'existing functional buttons must remain visible and untouched');
assert.ok(!js.includes('live.click()'),'the presentation module must not proxy or replace existing button behavior');
assert.ok(index.includes("ab.id='ord-add-btn'")&&index.includes("window.openOM(null)"),'the original Add new order button must continue opening the order form directly');
['localStorage','fbSet(','fetch(','removeItem(','innerHTML=\'\''].forEach(s=>assert.ok(!js.includes(s),`presentation module must not mutate app data: ${s}`));
assert.ok(index.includes('snippets/unified-graphic-headers-v1.css?v=230'));
assert.ok(index.includes('snippets/unified-graphic-headers-v1.js?v=230'));
assert.ok(index.includes('<meta name="rb-build" content="fix238">'));
assert.ok(index.includes('<div class="ct-title">Content Tracker')&&!index.includes('OLYMPPLUS Content Tracker'),'the Links title must omit the OLYMPPLUS prefix');
console.log('unified-graphic-headers-v1: all tests passed');
