const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const source=fs.readFileSync('snippets/workflow-ops-v1.js','utf8');
const store={rb_orders_v1:JSON.stringify([])};
const localStorage={getItem:k=>Object.prototype.hasOwnProperty.call(store,k)?store[k]:null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>{delete store[k]}};
const element=()=>({style:{},dataset:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){},insertBefore(){},querySelector(){return null},querySelectorAll(){return[]},addEventListener(){},closest(){return null}});
const document={documentElement:{},querySelector(){return null},getElementById(){return null},createElement:element,addEventListener(){},body:{appendChild(){}}};
const window={localStorage,_rbUser:{name:'View',role:'sup'},addEventListener(){},dispatchEvent(){},rbMultiTab:{id:'qa-tab'},document};
const context={window,document,localStorage,navigator:{onLine:false},MutationObserver:function(){this.observe=function(){}},setTimeout(fn){fn();return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},fetch(){return Promise.resolve({ok:true})},Blob:function(){},URL:{createObjectURL(){return''},revokeObjectURL(){}},confirm(){return true},getComputedStyle(){return{display:'none'}},console,Date,JSON,Math,Object,Array,String,Number,Promise};
context.global=context;vm.createContext(context);vm.runInContext(source,context);
const api=window._rbWorkflowOpsTest;
assert(api,'workflow operations test API must be available');
assert.deepStrictEqual(Array.from(api.changedFields({id:'GR001',title:'ก่อน'},{id:'GR001',title:'หลัง'})),['title']);
assert.equal(api.isMissing({title:'งาน',type:'ยิงแอด',deadline:'2026-08-30',assignee:'DOM'}),false);
assert.equal(api.isMissing({title:'งาน',type:'ยิงแอด',deadline:'',assignee:'DOM'}),true);
assert.equal(api.keyOf({_fbKey:'internal',id:'GR001'}),'internal');
assert.equal(api.stageCounts([{status:'pending',title:'A',type:'x',deadline:'2999-01-01',assignee:'DOM'},{status:'revision',title:'B',type:'x',deadline:'2999-01-01',assignee:'TER'}]).alert,1);
assert(source.includes("rb_order_write_queue_v1"),'health center must expose the existing safe sync queue');
assert(source.includes("workflow_snapshots/latest"),'Supervisor snapshot must have a shared latest backup');
assert(source.includes("workflow_locks"),'editing locks must cover multiple devices');
assert(source.includes("X-Firebase-ETag")&&source.includes("If-Match"),'cloud edit locks must use conditional writes');
assert(source.includes("ตรวจสอบและยืนยัน"),'bulk changes must require an explicit review action');
console.log('workflow-ops-v1: all tests passed');
